/* Definition editor contracts with a synthetic DOM. Native product verification
 * is separate: these do not claim browser layout or operational EES success. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),path=require('node:path');
const {renderer,run}=require('./ees_workspace_ui_fixture.cjs');
const source=fs.readFileSync(path.join(__dirname,'../branding/ees/ui/ees-work-designer.js'),'utf8');
const copy=value=>JSON.parse(JSON.stringify(value));
const toolExamples=[
 {id:'jira-query',name:'Jira 조회',description:'배포 전에 CR 승인 상태를 확인합니다.',kind:'read',match:{function:'jira_search_crs'}},
 {id:'service-status',name:'서비스 상태 조회',description:'EMS 서비스의 현재 상태를 확인합니다.',kind:'read',match:{function:'service_status'},requires_read_allowlist:true},
 {id:'collection-queue',name:'수집 대기열 조회',description:'EMS 수집 대기열을 확인합니다.',kind:'read',match:{function:'collection_queue'},requires_read_allowlist:true},
 {id:'restart-service',name:'서비스 재시작 요청',description:'EES에 서비스 재시작을 부탁합니다.',kind:'request',match:{tool_id:'ops',function:'restart_service'}},
];
const procedureExamples=[
 {id:'delivery_review',name:'배포 산출물 점검',description:'배포 자료를 순서대로 점검합니다.',category:'ops',mode:'periodic',execution_scope:null,stage_count:4,job_count:9,stages:[{name:'대상 확정',job_count:2},{name:'1차 점검',job_count:3},{name:'보완·재점검',job_count:2},{name:'조건부 승인 후속',job_count:2}],schedule_suggestion:'격주 화요일'},
 {id:'factory_rollout',name:'신규 공장 횡전개',description:'새 공장에 시스템을 설치합니다.',category:'setup',mode:'on_demand',execution_scope:'factory',stage_count:4,job_count:6,stages:[{name:'사전준비',job_count:1},{name:'AP·DB 인프라 준비',job_count:2},{name:'시스템 설치',job_count:1},{name:'시스템 간 인터페이스 확인',job_count:2}],schedule_suggestion:''},
 {id:'daily_check',name:'일일 시스템 점검',description:'매일 시스템 상태를 확인합니다.',category:'ops',mode:'periodic',execution_scope:null,stage_count:1,job_count:1,stages:[{name:'시스템 점검',job_count:1}],schedule_suggestion:'매일'},
];
const nativeFunction=(tool_id,name,kind='read',functionName='read')=>({name:tool_id==='jira'?'연결된 Jira':'연결된 '+tool_id,function_name:name,kind,reference:{tool_id,function:functionName,content_hash:'current'},schema:{type:'object',properties:{target:{type:'string'}}}});
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const decode=value=>String(value).replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&');
const attr=(text,name)=>decode(text.match(new RegExp('(?:^|\\s)'+name+'="([^"]*)"'))?.[1] || '');
function controls(html){const result=[];for(const m of html.matchAll(/<input\b([^>]*)>/g))result.push({name:attr(m[1],'name'),id:attr(m[1],'id'),value:attr(m[1],'value'),type:attr(m[1],'type'),checked:/\bchecked\b/.test(m[1]),disabled:/\bdisabled\b/.test(m[1])});for(const m of html.matchAll(/<textarea\b([^>]*)>([\s\S]*?)<\/textarea>/g))result.push({name:attr(m[1],'name'),id:attr(m[1],'id'),value:decode(m[2]),type:'textarea'});for(const m of html.matchAll(/<select\b([^>]*)>([\s\S]*?)<\/select>/g)){const options=[...m[2].matchAll(/<option\b([^>]*)>([^<]*)<\/option>/g)],o=options.find(o=>/\bselected\b/.test(o[1])) || options[0];result.push({name:attr(m[1],'name'),id:attr(m[1],'id'),value:o?attr(o[1],'value'):'',type:'select'});}return result;}
function definition(id='w'){return {id,name:'절차 '+id,system_id:'EMS',category:'ops',mode:'on_demand',nodes:{p:{id:'p',type:'p',parent:null,children:['t'],deps:[],name:'절차'},t:{id:'t',type:'t',parent:'p',children:['j'],deps:[],name:'단계'},j:{id:'j',type:'j',parent:'t',children:[],deps:[],name:'확인 작업',instructions:'원래 안내',mode:'human',inputs:[],result_block:'human_confirm',human_confirmation:true}}};}
function harness({cryptoProvider=crypto}={}){const h={writes:[],operations:[],reads:[],dialogs:[],proposals:[],markup:'',forms:{},buttons:[],fields:[]};h.workflows=new Map(['w','q'].map(id=>[id,{id,name:'절차 '+id,system_id:'EMS',can_manage:true,revision:1,published_version:null,draft:definition(id),validation:{revision:1,errors:[],warnings:[]},versions:[]}]));h.state={capabilities:{actor_id:'a',can_author:true,managed_systems:['EMS']},workflows:[...h.workflows.values()],workflow:h.workflows.get('w'),factories:[{id:'f',name:'공장'}],tools:[],native_functions:[],tool_examples:copy(toolExamples),procedure_examples:copy(procedureExamples)};h.selection={system_id:'EMS',workflow_id:'w',mode:'author',chat_id:'private-chat'};
 const noop=()=>{};let dialog=null;const host={contains:()=>false,querySelector(selector){if(selector==='.ew-author-ai')return h.composer;if(selector==='.ew-author-scroll')return {scrollTop:0};if(selector==='[data-author-status]')return {textContent:''};if(selector.startsWith('#'))return h.forms[selector.slice(1)] || h.fields.find(f=>f.id===selector.slice(1)) || null;const name=selector.match(/^\[name=([^\]]+)\]/)?.[1];return h.fields.find(f=>f.name===name) || null;},querySelectorAll(selector){if(selector==='[data-mutation]')return h.buttons.filter(b=>b.mutation);if(selector==='[data-author-action=procedure_cancel]')return h.buttons.filter(b=>b.dataset.authorAction==='procedure_cancel');return selector==='input,select,textarea'?h.fields:[];},set innerHTML(html){h.markup=html;const details=html.match(/<details class="ew-author-ai"([^>]*)>/);h.composer=details?{open:/\bopen\b/.test(details[1])}:null;h.fields=controls(html);h.forms={};for(const m of html.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/g)){const c=controls(m[2]);h.forms[attr(m[1],'id')]={controls:c};for(const field of c){const old=h.fields.findIndex(f=>f.name===field.name&&(field.type!=='radio'||f.value===field.value));if(old>=0)h.fields[old]=field;}}h.buttons=[...html.matchAll(/<button\b([^>]*)>/g)].map(m=>({dataset:{authorAction:attr(m[1],'data-author-action'),id:attr(m[1],'data-id'),tab:attr(m[1],'data-tab'),parent:attr(m[1],'data-parent')},disabled:/\bdisabled\b/.test(m[1]),mutation:/data-mutation/.test(m[1])}));},get innerHTML(){return h.markup;}};
 const callbacks={read:async query=>{h.reads.push(copy(query));if(h.readOverride)return h.readOverride(query);return {workflow:copy(h.workflows.get(query.workflow_id)),capabilities:copy(h.state.capabilities)};},command:async body=>{h.writes.push(copy(body));if(h.writeOverride)return h.writeOverride(body);if(body.action==='create_workflow'){const id='created-'+h.writes.length,draft=definition(id);draft.name=body.name;draft.system_id=body.system_id;draft.nodes={p:{id:'p',type:'p',name:body.name,parent:null,children:[]}};const record={id,name:body.name,system_id:body.system_id,can_manage:true,revision:1,published_version:null,draft,validation:null,versions:[]};h.workflows.set(id,record);h.state.workflows=[...h.workflows.values()];return {ok:true,workflow_id:id,revision:1,workflow:copy(record)};}const record=h.workflows.get(body.workflow_id);if(body.action==='save_draft'){record.draft=copy(body.definition);record.revision++;record.validation=null;return {ok:true,revision:record.revision};}if(body.action==='validate_workflow'){record.validation={revision:record.revision,errors:[],warnings:[]};return {ok:true,revision:record.revision,validation:copy(record.validation)};}if(body.action==='publish_workflow'){record.revision++;record.published_version=(record.published_version || 0)+1;record.validation=null;return {ok:true,revision:record.revision,version:record.published_version};}return {ok:true};},operationsCommand:async body=>{h.operations.push(copy(body));if(h.operationOverride)return h.operationOverride(body);return {ok:true,tool:{...copy(body.tool || h.state.tools.find(t=>t.id===body.tool_contract_id)),id:'tool',revision:2,state:body.action==='tool_submit'?'review_requested':'draft'}};},models:async()=>h.modelsOverride?h.modelsOverride():{models:[{id:'m',name:'Native 모델'}],preferred:['m']},propose:async body=>{h.proposals.push(body);return h.proposeOverride?h.proposeOverride(body):{workflow_id:body.workflow_id,base_revision:body.expected_revision,context_id:body.context_id,definition:{...copy(body.definition),name:'AI 제안'},summary:'초안 제안'};},openWorkflow:async id=>{h.selection.workflow_id=id;h.state.workflow=h.workflows.get(id) || null;h.designer.render({state:h.state,selection:h.selection,host});},changed:async()=>{h.state.workflow=h.workflows.get(h.selection.workflow_id) || null;h.designer.render({state:h.state,selection:h.selection,host});}};
 const workUI={newId:run(renderer({crypto:cryptoProvider}),'workUI.newId'),esc:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),icon:id=>'<img src="/_ees13/v4/'+id+'.svg" alt="">',$:selector=>selector==='#ees-work-dialog'?dialog:null,dialog:options=>{h.dialogHistory ||= [];h.dialogHistory.push(options);const answer=h.dialogs.shift();assert.notEqual(answer,undefined,'dialog answer is explicit');const listeners={};dialog={addEventListener:(event,cb)=>{(listeners[event] ||= []).push(cb);},querySelectorAll:()=>Object.entries(answer || {}).map(([name,value])=>({name,value,type:typeof value==='boolean'?'checkbox':'text',checked:!!value}))};return Promise.resolve().then(async()=>{await h.dialogHook?.();for(const listener of listeners.click || [])listener({target:{closest:selector=>selector==='[data-dialog-confirm]'?true:null},preventDefault:noop,stopPropagation:noop});return answer!==null;});}};
 const FormData=class{constructor(form){this.data=form.controls.filter(c=>c.name&&!c.disabled&&(!['checkbox','radio'].includes(c.type)||c.checked)).map(c=>[c.name,c.value || (c.type==='checkbox'?'on':'')]);}has(key){return this.data.some(([name])=>name===key);}get(key){return this.data.find(([name])=>name===key)?.[1]??null;}getAll(key){return this.data.filter(([name])=>name===key).map(([,v])=>v);}entries(){return this.data.values();}};
 const context={workUI,crypto:cryptoProvider,AbortController,FormData,document:{activeElement:null},console};vm.createContext(context);vm.runInContext(source,context);context.callbacks=callbacks;h.designer=vm.runInContext('createWorkDesigner({callbacks})',context);h.helpers=vm.runInContext('workAuthoring',context);h.host=host;h.callbacks=callbacks;
 h.render=()=>h.designer.render({state:h.state,selection:h.selection,host});h.render();
 h.click=(action,data={})=>{const control={dataset:{authorAction:action,...data}};h.designer.handleEvent({type:'click',target:{closest:selector=>selector==='#ees-work-designer'?host:control}});};
 h.field=(name,value,event='input')=>{const field=h.fields.find(f=>f.name===name || f.id===name);assert.ok(field,'field '+name);if(field.type==='checkbox')field.checked=value;else field.value=value;h.designer.handleEvent({type:event,target:{...field,closest:()=>host}});};
 h.pick=async(id)=>{h.click('tool_create');await flush();h.click('tool_pick',{id});await flush();};h.example=async(id)=>{h.click('tool_create');await flush();h.click('tool_example',{id});await flush();};h.chooseTemplate=async value=>{const field=h.fields.find(field=>field.name==='procedure_template'&&field.value===value);assert.ok(field,'procedure radio '+value);for(const item of h.fields.filter(item=>item.name==='procedure_template'))item.checked=item===field;h.designer.handleEvent({type:'change',target:{...field,closest:()=>host}});await flush();};h.node=async(id='j')=>{h.click('node',{id});await flush();};h.open=id=>callbacks.openWorkflow(id);h.draft=()=>copy(h.designer.readDraft());return h;
}

test('new Figma authoring keeps Native conversation untouched and has exact right-panel structure',async()=>{const h=harness();await flush();assert.match(h.markup,/class="ew-author(?:\s[^"]*)?"/);assert.match(h.markup,/구조/);assert.doesNotMatch(source,/hideWorkspaceContent|chat\.hidden|ees-work-native-hidden/);});
test('empty workspace listing does not create drafts or runs',async()=>{const h=harness();h.state.workflows=[];await h.open('');assert.match(h.markup,/아직 업무 절차가 없습니다/);assert.equal(h.writes.length,0);assert.equal(h.operations.length,0);});
test('direct editing saves only the chosen definition with current revision and request ID',async()=>{const h=harness();await h.node();h.field('instructions','직접 수정');h.click('save');await flush();assert.equal(h.writes[0].action,'save_draft');assert.equal(h.writes[0].workflow_id,'w');assert.equal(h.writes[0].expected_revision,1);assert.ok(h.writes[0].request_id);assert.equal(h.writes[0].definition.nodes.j.instructions,'직접 수정');assert.equal(h.workflows.get('q').draft.nodes.j.instructions,'원래 안내');assert.equal(h.draft().revision,2);assert.equal(h.draft().dirty,false);});
test('dirty drafts and per-workflow node selection survive navigation',async()=>{const h=harness();await h.node();h.field('instructions','W 비공개 초안');await h.open('q');await h.node();h.field('instructions','Q 초안');await h.open('w');assert.equal(h.draft().definition.nodes.j.instructions,'W 비공개 초안');assert.match(h.markup,/W 비공개 초안/);assert.equal(h.writes.length,0);});
test('typing during save preserves later edits and acknowledges only own base revision',async()=>{const h=harness(),pending=deferred();await h.node();h.field('instructions','저장 요청');h.writeOverride=()=>pending.promise;h.click('save');await flush();h.field('instructions','요청 뒤 새 글');pending.resolve({ok:true,revision:2});await flush();assert.equal(h.draft().definition.nodes.j.instructions,'요청 뒤 새 글');assert.equal(h.draft().revision,2);assert.equal(h.draft().dirty,true);});
test('same failed payload reuses request identity; different payload receives new identity',async()=>{const h=harness();await h.node();h.writeOverride=async()=>{throw new Error('response lost');};h.field('instructions','첫 글');h.click('save');await flush();h.click('save');await flush();assert.equal(h.writes[0].request_id,h.writes[1].request_id);h.field('instructions','다른 글');h.click('save');await flush();assert.notEqual(h.writes[1].request_id,h.writes[2].request_id);});
test('revision conflict preserves unsaved text and never silently rebases',async()=>{const h=harness();await h.node();h.field('instructions','충돌 전 글');h.writeOverride=async()=>({ok:false,error:{code:'revision_conflict',message:'다른 담당자가 저장했습니다.'}});h.click('save');await flush();assert.equal(h.draft().revision,1);assert.equal(h.draft().dirty,true);assert.equal(h.draft().definition.nodes.j.instructions,'충돌 전 글');assert.match(h.markup,/최신 저장본과 비교/);});
test('authorization denial preserves private draft and blocks subsequent mutation',async()=>{const h=harness();await h.node();h.field('instructions','권한 회수 전 글');h.writeOverride=async()=>{throw Object.assign(new Error('권한 회수'),{status:403});};h.click('save');await flush();h.click('save');await flush();assert.equal(h.writes.length,1);assert.equal(h.designer.canAuthor(),false);assert.equal(h.draft().definition.nodes.j.instructions,'권한 회수 전 글');});
test('account reset rejects late save and clears draft cache',async()=>{const h=harness(),pending=deferred();await h.node();h.field('instructions','A 비공개');h.writeOverride=()=>pending.promise;h.click('save');await flush();h.state.capabilities.actor_id='b';h.render();pending.resolve({ok:true,revision:99});await flush();assert.doesNotMatch(h.markup,/A 비공개/);assert.notEqual(h.draft().revision,99);});
test('late workflow reads cannot overwrite newer selection',async()=>{const h=harness(),pending=deferred();h.state.workflow=null;h.state.workflows=h.state.workflows.map(({draft,...rest})=>rest);h.readOverride=q=>q.workflow_id==='q'?pending.promise:Promise.resolve({workflow:copy(h.workflows.get('w'))});await h.open('q');await h.open('w');pending.resolve({workflow:copy(h.workflows.get('q'))});await flush();assert.equal(h.draft().definition.id,'w');});
test('publish requires exact saved validated revision and explicit confirmation',async()=>{const h=harness();await h.node();h.field('instructions','저장 전 변경');h.click('publish');await flush();assert.equal(h.writes.length,0);h.click('save');await flush();h.click('validate');await flush();h.dialogs.push(null);h.click('publish');await flush();assert.equal(h.writes.filter(w=>w.action==='publish_workflow').length,0);h.dialogs.push({});h.click('publish');await flush();const body=h.writes.at(-1);assert.equal(body.action,'publish_workflow');assert.equal(body.expected_revision,2);assert.match(h.dialogHistory.at(-1).html,/기존 진행 건은 바뀌지 않습니다/);});
test('all eight input types and result blocks are represented without workflow-specific HTML',()=>{const h=harness();assert.equal(Object.keys(h.helpers.inputTypes).length,8);assert.equal(Object.keys(h.helpers.blocks).length,8);assert.deepEqual(Object.keys(h.helpers.inputTypes),['text','number','datetime','single','multi','list','person','boolean']);assert.ok(h.helpers.blocks.change_request);});
test('declared input and tool argument binding are saved together',async()=>{const h=harness();await h.node();h.dialogs.push({id:'project',name:'Jira 프로젝트',type:'single',scope:'workflow',required:true,unit:'',options_source:'manual',options:'PROJA\nPROJB',depends_on:'',tool_argument:'project_key'});h.click('input_add');await flush();const node=h.draft().definition.nodes.j;assert.equal(node.inputs[0].id,'project');assert.equal(node.inputs[0].required,true);assert.deepEqual(node.inputs[0].options,['PROJA','PROJB']);assert.deepEqual(node.argument_bindings.project_key,{input:'project'});assert.equal(node.inputs[0].scope,'workflow');});
test('stage/job insertion and removal keep referential defects visible for publish validation',async()=>{const h=harness();h.click('add_stage');await flush();const stage=Object.values(h.draft().definition.nodes).find(n=>n.id.startsWith('stage-'));assert.equal(stage.parent,'p');h.click('add_job',{parent:stage.id});await flush();const job=Object.values(h.draft().definition.nodes).find(n=>n.id.startsWith('job-'));assert.equal(job.parent,stage.id);const d=h.draft().definition;d.nodes.j.deps=[job.id];const removed=h.helpers.removeNode(d,stage.id);assert.ok(removed.includes(job.id));assert.deepEqual(d.nodes.j.deps,[job.id]);assert.ok(d.nodes.j);});
test('factory overrides distinguish an explicit empty value, zero, and absent value',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.inputs=[{id:'target',name:'대상',type:'text',scope:'workflow'},{id:'limit',name:'한도',type:'number',scope:'workflow'},{id:'unused',name:'기본 사용',type:'text',scope:'workflow'}];h.render();h.click('factory',{id:'f'});h.dialogs.push({'override:target':true,'value:target':'','override:limit':true,'value:limit':'0','override:unused':false,'value:unused':'무시'});h.click('factory_settings');await flush();const body=h.writes.at(-1);assert.equal(body.action,'save_settings');assert.equal(body.factory_id,'f');assert.deepEqual(body.values,{target:'',limit:0});});
test('AI model selection uses permitted explicit choice/default and no silent first-of-many fallback',()=>{const h=harness();assert.equal(h.helpers.chooseModel({models:[]}).selected,'');assert.equal(h.helpers.chooseModel({models:[{id:'one'}]}).selected,'one');assert.equal(h.helpers.chooseModel({models:[{id:'a'},{id:'b'}]}).selected,'');assert.equal(h.helpers.chooseModel({models:[{id:'a'},{id:'b'}],preferred:['b']}).selected,'b');});
test('0 models and model listing failure preserve direct authoring and save',async()=>{for(const fails of [false,true]){const h=harness();h.designer.reset();h.modelsOverride=async()=>{if(fails)throw new Error('no model listing');return {models:[]};};h.render();await flush();assert.match(h.markup,fails?/모델 목록을 읽지 못했습니다/:/사용할 수 있는 모델이 없습니다/);await h.node();h.field('instructions','모델 없이 작성');h.click('save');await flush();assert.equal(h.writes[0].definition.nodes.j.instructions,'모델 없이 작성');assert.equal(h.proposals.length,0);}});
test('one model hides the selector and multiple models require Native choice',async()=>{const h=harness();await flush();assert.doesNotMatch(h.markup,/name="model_id"/);h.designer.reset();h.modelsOverride=async()=>({models:[{id:'a'},{id:'b'}]});h.render();await flush();assert.match(h.markup,/name="model_id"/);assert.equal(h.buttons.find(b=>b.dataset.authorAction==='ai_propose').disabled,true);});
test('AI proposal is a preview and explicit local application never saves or publishes',async()=>{const h=harness();await flush();h.field('ai_prompt','점검 절차를 작성해 줘');h.click('ai_propose');await flush();assert.equal(h.draft().definition.name,'절차 w');assert.match(h.markup,/편집 초안에 반영/);assert.equal(h.writes.length,0);h.click('ai_apply');await flush();assert.equal(h.draft().definition.name,'AI 제안');assert.equal(h.draft().dirty,true);assert.equal(h.writes.length,0);});
test('late AI proposal after workflow navigation or manual edits is never applied',async()=>{for(const navigate of [false,true]){const h=harness(),pending=deferred();await flush();h.proposeOverride=()=>pending.promise;h.field('ai_prompt','늦은 제안');h.click('ai_propose');await flush();const request=h.proposals[0];if(navigate)await h.open('q');else{await h.node();h.field('instructions','새로 직접 작성');}pending.resolve({workflow_id:'w',base_revision:1,context_id:request.context_id,definition:{...definition(),name:'적용 금지'}});await flush();assert.notEqual(h.draft().definition.name,'적용 금지');assert.equal(h.writes.length,0);}});
test('malformed and cross-context AI output cannot create arbitrary editor state',()=>{const h=harness();const context={workflowId:'w',revision:1,contextId:'c'},good={workflow_id:'w',base_revision:1,context_id:'c',definition:definition()};for(const bad of ['not json',{...good,workflow_id:'q'},{...good,base_revision:2},{...good,context_id:'d'},{...good,definition:{nodes:[{id:'x',type:'script'}]}}])assert.throws(()=>h.helpers.proposal(bad,context));assert.equal(h.helpers.proposal(good,context).definition.id,'w');});
test('Native chat proposals require exact personal conversation and target revision',()=>{const h=harness(),proposal={workflow_id:'w',base_revision:1,context_id:'c',definition:definition()};assert.throws(()=>h.designer.acceptProposal(proposal,{chatId:'someone-else'}));assert.throws(()=>h.designer.acceptProposal({...proposal,base_revision:2},{chatId:'private-chat'}));assert.equal(h.designer.acceptProposal(proposal,{chatId:'private-chat'}).saved,false);assert.equal(h.writes.length,0);});
test('B5 stores inspected Native function reference and immutable input schema',async()=>{const h=harness();h.selection.tab='tools';h.state.native_functions=[{name:'Jira',kind:'read',reference:{tool_id:'jira',function:'search_issues',code_hash:'sha'},schema:{type:'object',properties:{project:{type:'string'}}}}];h.render();await h.pick('jira:search_issues');h.field('name','CR 조회');h.click('tool_save');await flush();assert.equal(h.operations[0].action,'tool_save');assert.deepEqual(h.operations[0].tool.reference,{tool_id:'jira',function:'search_issues',code_hash:'sha'});assert.deepEqual(h.operations[0].tool.input_schema,{type:'object',properties:{project:{type:'string'}}});assert.equal(h.writes.length,0);});
test('tool review is an explicit operation with designated contract revision',async()=>{const h=harness();h.selection.tab='tools';h.state.tools=[{id:'tool',name:'조회',kind:'read',system_id:'EMS',revision:3,state:'review_requested'}];h.render();h.click('tool_open',{id:'tool'});h.dialogs.push({review_note:'기능과 가이드 확인',review_evidence:'repo/commit · contract test · local synthetic environment'});h.click('tool_approve');await flush();assert.equal(h.operations[0].action,'tool_review');assert.equal(h.operations[0].decision,'approve');assert.equal(h.operations[0].tool_contract_id,'tool');assert.equal(h.operations[0].expected_revision,3);assert.match(h.operations[0].evidence,/contract test/);});
test('unavailable EES definitions are explicit and never turn into fake request success',async()=>{const h=harness();h.selection.tab='tools';h.render();await h.example('restart-service');assert.match(h.markup,/필요한 기능이 아직 연결되지 않았습니다/);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,true);assert.equal(h.operations.length,0);assert.doesNotMatch(h.markup,/실행 성공/);});
test('unsafe labels and instructions are escaped in the editor',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.name='<img onerror="attack">';h.workflows.get('w').draft.nodes.j.instructions='<script>attack()</script>';h.render();await h.node();assert.doesNotMatch(h.markup,/<script>/);assert.match(h.markup,/&lt;script&gt;/);assert.match(h.markup,/&lt;img/);});

test('opening a form and reading a draft never marks unchanged definitions dirty',async()=>{const h=harness(),original=copy(h.workflows.get('w').draft);await h.node();assert.deepEqual(h.draft().definition,original);assert.equal(h.draft().dirty,false);h.click('tab',{tab:'schedule'});await flush();assert.deepEqual(h.draft().definition,original);assert.equal(h.draft().dirty,false);});
test('opaque Native references, dangling dependencies and compound conditions survive unrelated edits',async()=>{const h=harness(),node=h.workflows.get('w').draft.nodes.j;node.tool_reference={tool_id:'private',function:'read',code_hash:'old'};node.deps=['removed'];node.argument_bindings={target:{input:'hidden-input'}};node.condition={all:[{field:'country',op:'eq',value:'KR'},{field:'interface',op:'eq',value:false}]};h.render();await h.node();h.field('instructions','안내만 수정');const result=h.draft().definition.nodes.j;assert.deepEqual(result.tool_reference,node.tool_reference);assert.deepEqual(result.deps,['removed']);assert.deepEqual(result.condition,node.condition);assert.deepEqual(result.argument_bindings,node.argument_bindings);});
test('factory settings preserve all eight input value types without coercing omitted fields',async()=>{const h=harness();const inputs=Object.keys(h.helpers.inputTypes).map((type,i)=>({id:'f'+i,name:type,type,scope:'workflow',options:['a','b']}));h.workflows.get('w').draft.nodes.j.inputs=inputs;h.render();const raw=['text','0','2026-10-03T10:30','a',['a','b'],'first\nsecond','group:operators','false'];const answer={};for(let i=0;i<inputs.length;i++){answer['override:f'+i]=true;answer['value:f'+i]=raw[i];}h.dialogs.push(answer);h.click('factory_settings');await flush();assert.deepEqual(h.writes.at(-1).values,{f0:'text',f1:0,f2:'2026-10-03T10:30',f3:'a',f4:['a','b'],f5:['first','second'],f6:{kind:'group',id:'operators'},f7:false});});
test('late model listing after reset cannot overwrite the new account choice',async()=>{const h=harness(),pending=deferred();h.designer.reset();h.modelsOverride=()=>pending.promise;h.render();await flush();h.designer.reset();h.modelsOverride=async()=>({models:[{id:'b',name:'B 모델'}]});h.state.capabilities.actor_id='b';h.render();await flush();pending.resolve({models:[{id:'a',name:'A 비공개 모델'}]});await flush();assert.match(h.markup,/B 모델/);assert.doesNotMatch(h.markup,/A 비공개 모델/);});

test('a confirmation opened for one workflow cannot publish after context changes',async()=>{const h=harness();h.dialogs.push({});h.dialogHook=()=>h.open('q');h.click('publish');await flush();assert.equal(h.writes.length,0);assert.equal(h.draft().definition.id,'q');});
test('conflict comparison can discard only by explicit choice and load exact new revision',async()=>{const h=harness();await h.node();h.field('instructions','내 변경');h.workflows.get('w').revision=3;h.workflows.get('w').draft.nodes.j.instructions='서버 변경';h.dialogs.push({choice:'keep'});h.click('compare');await flush();assert.equal(h.draft().definition.nodes.j.instructions,'내 변경');assert.equal(h.draft().revision,1);h.dialogs.push({choice:'discard'});h.click('compare');await flush();assert.equal(h.draft().definition.nodes.j.instructions,'서버 변경');assert.equal(h.draft().revision,3);assert.equal(h.draft().dirty,false);});
test('tool navigation returns to workflow editor without retaining tool-only surface',async()=>{const h=harness();h.selection.tab='tools';h.render();assert.match(h.markup,/>도구</);h.selection.tab='overview';h.render();assert.match(h.markup,/>업무 절차</);assert.match(h.markup,/절차 설정/);});
test('job trigger persists a bounded offset instead of a browser timer',async()=>{const h=harness();await h.node();h.field('trigger_kind','offset','change');h.field('trigger_offset','3600');assert.deepEqual(h.draft().definition.nodes.j.trigger,{offset_seconds:3600});assert.doesNotMatch(source,/setInterval|setTimeout/);});
test('published periodic schedule explicitly pins user, version, jobs, timezone and delegation',async()=>{const h=harness(),record=h.workflows.get('w');record.published_version=2;record.draft.mode='periodic';record.draft.schedule={timezone:'Asia/Seoul',anchor:'2026-10-05T09:00',frequency:'weekly',interval:1};record.draft.nodes.j.mode='tool';record.published=copy(record.draft);h.render();h.dialogs.push({timezone:'Asia/Seoul',anchor:'2026-10-05T09:00',frequency:'weekly',interval:'1',grace_seconds:'300',delegated:true,'job:j':true});h.click('schedule_create');await flush();assert.equal(h.operations[0].action,'schedule_save');assert.equal(h.operations[0].expected_revision,0);assert.equal(h.operations[0].schedule.identity_user_id,'a');assert.equal(h.operations[0].schedule.version,2);assert.equal(h.operations[0].schedule.delegated,true);assert.deepEqual(h.operations[0].schedule.job_ids,['j']);assert.equal(h.operations[0].schedule.catch_up,'miss');assert.equal(h.writes.length,0);});

test('Native skills remain optional and only current permitted IDs are added to a job',async()=>{const h=harness();h.callbacks.resources=async()=>({available:true,skills:[{id:'native-skill',name:'사용자 지침',revision:4}]});h.render();await flush();await h.node();assert.match(h.markup,/사용자 지침/);h.field('skills',true,'change');h.click('save');await flush();assert.deepEqual(h.writes[0].definition.nodes.j.skills,['native-skill']);assert.equal(JSON.stringify(h.writes[0]).includes('skill body'),false);});
test('unavailable Native skills preserve opaque references and do not block direct human work',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.skills=['opaque-skill'];h.callbacks.resources=async()=>({available:false,skills:[]});h.render();await flush();await h.node();h.field('instructions','직접 작성 가능');h.click('save');await flush();assert.deepEqual(h.writes[0].definition.nodes.j.skills,['opaque-skill']);assert.equal(h.writes[0].definition.nodes.j.mode,'human');assert.match(h.markup,/기존 연결은 유지/);});
test('a late skill-list response cannot expose the previous account metadata',async()=>{const h=harness(),pending=deferred();h.callbacks.resources=()=>pending.promise;h.render();await flush();h.designer.reset();h.state.capabilities.actor_id='b';h.callbacks.resources=async()=>({available:true,skills:[]});h.render();await flush();pending.resolve({available:true,skills:[{id:'a-private',name:'A 비공개 지침'}]});await flush();await h.node();assert.doesNotMatch(h.markup,/A 비공개 지침/);});

test('dynamic Jira options pin discovered Native reference and declared project dependency without static examples',async()=>{const h=harness(),reference={tool_id:'jira-native',function:'jira_project_metadata',revision:7,content_hash:'current'};h.state.native_functions=[{kind:'read',name:'Jira metadata',reference}];await h.node();h.dialogs.push({id:'cr_status',name:'CR 상태',type:'multi',scope:'run',required:true,options_source:'tool',source_reference:'jira-native:jira_project_metadata',source_list:'statuses',depends_on:'project',options:'must disappear',tool_argument:'status_ids'});h.click('input_add');await flush();const field=h.draft().definition.nodes.j.inputs[0];assert.deepEqual(field.depends_on,['project']);assert.deepEqual(field.options,[]);assert.deepEqual(field.options_query,{reference,argument_bindings:{project_key:{input:'project'}},result_path:['statuses'],value_field:'id',label_field:'name'});assert.equal(field.source_reference,undefined);});
test('dynamic options cannot invent an unconfigured Native reference or fall back to static entries',async()=>{const h=harness();await h.node();h.dialogs.push({id:'project',name:'프로젝트',type:'single',scope:'run',options_source:'tool',source_reference:'not-permitted',source_list:'projects',options:'EMS'});h.click('input_add');await flush();assert.deepEqual(h.draft().definition.nodes.j.inputs,[]);assert.match(h.markup,/현재 계정으로 확인한 선택지 조회 기능/);});
test('common options use current authorized entities and preserve an opaque tool source on description edit',async()=>{const h=harness(),query={reference:{tool_id:'private',function:'custom'},argument_bindings:{x:{constant:'fixed'}},result_path:['permitted'],value_field:'key',label_field:'title'};h.workflows.get('w').draft.nodes.j.inputs=[{id:'opaque',name:'기존',type:'single',scope:'run',options_source:'tool',options_query:query,depends_on:[]}];h.render();await h.node();h.dialogs.push({id:'opaque',name:'설명만 변경',type:'single',scope:'run',options_source:'tool',source_reference:'private:custom'});h.click('input_edit',{id:'opaque'});await flush();assert.deepEqual(h.draft().definition.nodes.j.inputs[0].options_query,query);h.dialogs.push({id:'group',name:'그룹',type:'single',scope:'run',options_source:'common',source_common:'groups',options:'fake'});h.click('input_add');await flush();assert.deepEqual(h.draft().definition.nodes.j.inputs[1].options_query,{kind:'groups'});assert.deepEqual(h.draft().definition.nodes.j.inputs[1].options,[]);});
test('tool selection pins contract revision and unrelated edits cannot silently upgrade an old published reference',async()=>{const h=harness(),reference={tool_id:'native',function:'read',content_hash:'v2'};h.state.tools=[{id:'approved-tool',state:'approved',revision:2,reference}];await h.node();h.field('tool_contract_id','approved-tool','change');assert.equal(h.draft().definition.nodes.j.tool_contract_revision,2);h.state.tools[0].revision=3;h.state.tools[0].reference={...reference,content_hash:'v3'};h.field('instructions','안내만 수정');const node=h.draft().definition.nodes.j;assert.equal(node.tool_contract_revision,2);assert.equal(node.tool_reference.content_hash,'v2');});
test('AI item verdicts declare their source job and EES requests retain explicit effect criteria',async()=>{const h=harness();await h.node();h.field('mode','ai','change');h.field('result_block','item_verdict','change');h.field('result_source_job_id','cr-list','change');assert.equal(h.draft().definition.nodes.j.result_source_job_id,'cr-list');h.field('result_block','change_request','change');h.field('effect_job_id','verify');h.field('effect_description','승인된 상태 조회에서 효과를 확인');assert.deepEqual(h.draft().definition.nodes.j.effect_criterion,{job_id:'verify',description:'승인된 상태 조회에서 효과를 확인'});});
test('confirmed list bindings and deadline rules store declared references instead of browser calculations',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.inputs=[{id:'deployment',name:'배포일',type:'datetime',scope:'run'}];h.render();await h.node();h.field('mode','tool','change');h.field('result_argument','issue_keys');h.field('result_job_id','confirmed-list','change');h.field('deadline_input','deployment','change');h.field('deadline_offset','-2');h.field('deadline_timezone','Asia/Seoul');h.field('deadline_calendar','business','change');const node=h.draft().definition.nodes.j;assert.deepEqual(node.argument_bindings.issue_keys,{result:{job_id:'confirmed-list',path:['items'],value_field:'id',confirmed:true}});assert.deepEqual(node.deadline,{input:'deployment',offset_days:-2,timezone:'Asia/Seoul',calendar:'business'});assert.equal(node.due_at,undefined);});
test('a result report can record all resolved verdicts without converting unknown CRs into approved completion',async()=>{const h=harness();await h.node();h.field('mode','ai','change');h.field('result_block','ai_review','change');h.field('dependency_policy','all_resolved','change');assert.equal(h.draft().definition.nodes.j.dependency_policy,'all_resolved');assert.equal(h.draft().definition.nodes.j.human_confirmation,true);});
test('factory settings fetch dynamic choices from the saved definition and never substitute examples after failure',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.inputs=[{id:'project',name:'실제 프로젝트',type:'single',scope:'workflow',options_source:'tool',options_query:{reference:{tool_id:'jira',function:'jira_project_metadata',content_hash:'x'},argument_bindings:{project_key:{constant:''}},result_path:['projects'],value_field:'id',label_field:'name'}}];h.render();const queries=[];h.callbacks.options=async body=>{queries.push(copy(body));return {ok:true,options:[{id:'APPX',name:'실제 프로젝트 표시'}]};};h.dialogs.push({'override:project':true,'value:project':'APPX'});h.click('factory_settings');await flush();assert.equal(queries[0].job_id,'j');assert.equal(queries[0].workflow_id,'w');assert.match(h.dialogHistory.at(-1).html,/실제 프로젝트 표시/);assert.deepEqual(h.writes.at(-1).values,{project:'APPX'});h.callbacks.options=async()=>{throw new Error('현재 권한 없음');};h.dialogs.push({'override:project':true,'value:project':'EMS'});const before=h.writes.length;h.click('factory_settings');await flush();assert.equal(h.writes.length,before);assert.match(h.markup,/현재 선택지를 확인한 뒤/);});
test('person settings use current Native people metadata without making free-text users',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.inputs=[{id:'reviewer',name:'검토자',type:'person',scope:'workflow'}];h.state.people=[{id:'a',name:'실제 사용자',value:{kind:'user',id:'a'}},{id:'g',name:'실제 그룹',value:{kind:'group',id:'g'}}];h.render();h.dialogs.push({'override:reviewer':true,'value:reviewer':'group:g'});h.click('factory_settings');await flush();assert.match(h.dialogHistory.at(-1).html,/실제 사용자/);assert.match(h.dialogHistory.at(-1).html,/실제 그룹/);assert.deepEqual(h.writes.at(-1).values,{reviewer:{kind:'group',id:'g'}});});

test('Native proposal review is visibly open from a selected job and non-structure tabs without saving',async()=>{for(const view of ['job','history','schedule','rules']){const h=harness();if(view==='job')await h.node();else{h.click('tab',{tab:view});await flush();}const proposal={workflow_id:'w',base_revision:1,context_id:'native-context',definition:{...definition(),name:'대화 제안'}};h.designer.acceptProposal(proposal,{chatId:'private-chat'});assert.match(h.markup,/<details class="ew-author-ai" open>/);assert.equal(h.buttons.filter(b=>b.dataset.authorAction==='ai_apply').length,1);assert.equal(h.buttons.filter(b=>b.dataset.authorAction==='ai_discard').length,1);if(view==='job')assert.match(h.markup,/id="ew-author-node"/);assert.equal(h.draft().definition.name,'절차 w');assert.equal(h.writes.length,0);h.click('ai_apply');await flush();assert.equal(h.draft().definition.name,'대화 제안');assert.equal(h.draft().dirty,true);assert.equal(h.writes.length,0);}});
test('job assignee uses only current Native user/group identities and persists exact principal',async()=>{const h=harness();h.state.people=[{id:'u',name:'현재 사용자',value:{kind:'user',id:'u'}},{id:'g',name:'현재 그룹',value:{kind:'group',id:'g'}}];h.render();await h.node();assert.match(h.markup,/현재 사용자/);assert.match(h.markup,/현재 그룹/);h.field('assignee','group:g','change');h.click('save');await flush();assert.deepEqual(h.writes[0].definition.nodes.j.assignee,{kind:'group',id:'g'});h.field('assignee','user:invented','change');assert.deepEqual(h.draft().definition.nodes.j.assignee,{kind:'group',id:'g'});h.field('assignee','','change');assert.equal(h.draft().definition.nodes.j.assignee,undefined);});
test('unavailable existing assignee is preserved on unrelated edits and removed only explicitly',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.assignee={kind:'user',id:'opaque-prior-user'};h.render();await h.node();assert.match(h.markup,/기존 담당자 · 현재 접근 확인 필요/);h.field('instructions','안내 수정');assert.deepEqual(h.draft().definition.nodes.j.assignee,{kind:'user',id:'opaque-prior-user'});h.field('assignee','','change');assert.equal(h.draft().definition.nodes.j.assignee,undefined);});
test('B5 explicitly authored output contract saves an object while Native input schema stays authoritative',async()=>{const h=harness(),schema={type:'object',properties:{ticket:{type:'string'},status:{type:'string'}},required:['ticket']};h.selection.tab='tools';h.state.native_functions=[{name:'Registered request',kind:'request',reference:{tool_id:'current',function:'request',content_hash:'actual'},schema:{type:'object',properties:{target:{type:'string'}}}}];h.render();await h.pick('current:request');h.field('output_schema_json',JSON.stringify(schema));h.field('guide_url','https://example.invalid/verified-guide');h.click('tool_save');await flush();assert.deepEqual(h.operations[0].tool.output_schema,schema);assert.deepEqual(h.operations[0].tool.input_schema,{type:'object',properties:{target:{type:'string'}}});assert.equal(h.operations[0].tool.output_schema_json,undefined);assert.match(h.markup,/가이드 문서/);assert.match(h.markup,/필수/);assert.doesNotMatch(h.markup,/name="input_schema/);});
test('invalid output contract remains editable and cannot save or submit stale schema',async()=>{for(const invalid of ['{bad json','[]','null','"schema"']){const h=harness();h.selection.tab='tools';h.state.tools=[{id:'tool',name:'요청',kind:'request',revision:3,state:'draft',output_schema:{type:'object'}}];h.render();h.click('tool_open',{id:'tool'});await flush();h.field('output_schema_json',invalid);h.click('tool_save');await flush();assert.equal(h.operations.length,0);assert.equal(h.fields.find(f=>f.name==='output_schema_json').value,invalid);assert.match(h.markup,/올바른 JSON Schema 객체/);h.click('tool_review');await flush();assert.equal(h.operations.length,0);h.field('output_schema_json','{"type":"object"}');h.click('tool_save');await flush();assert.deepEqual(h.operations[0].tool.output_schema,{type:'object'});}});
test('existing output contract is not silently replaced by metadata when unrelated fields change',async()=>{const h=harness(),reference={tool_id:'current',function:'read'},saved={type:'object',properties:{reviewed:{type:'boolean'}}};h.selection.tab='tools';h.state.tools=[{id:'tool',name:'조회',kind:'read',revision:4,state:'draft',reference,output_schema:saved}];h.state.native_functions=[{name:'조회',kind:'read',reference,schema:{type:'object'},output_schema:{type:'object',properties:{different:{type:'string'}}}}];h.render();h.click('tool_open',{id:'tool'});await flush();h.field('description','안내만 수정');h.click('tool_save');await flush();assert.deepEqual(h.operations[0].tool.output_schema,saved);});
test('input deletion requires confirmation and retains dangling bindings for publish validation',async()=>{const h=harness(),node=h.workflows.get('w').draft.nodes.j;node.inputs=[{id:'date',name:'기준 날짜',type:'datetime',scope:'run'}];node.argument_bindings={target:{input:'date'}};node.deadline={input:'date',offset_days:-1,timezone:'Asia/Seoul',calendar:'calendar'};h.render();await h.node();h.dialogs.push(null);h.click('input_delete',{id:'date'});await flush();assert.equal(h.draft().definition.nodes.j.inputs.length,1);h.dialogs.push({});h.click('input_delete',{id:'date'});await flush();assert.deepEqual(h.draft().definition.nodes.j.inputs,[]);assert.deepEqual(h.draft().definition.nodes.j.argument_bindings,{target:{input:'date'}});assert.equal(h.draft().definition.nodes.j.deadline.input,'date');assert.equal(h.writes.length,0);});
test('input deletion confirmation cannot mutate a different workflow after navigation',async()=>{const h=harness();h.workflows.get('w').draft.nodes.j.inputs=[{id:'field',name:'입력',type:'text'}];h.render();await h.node();h.dialogs.push({});h.dialogHook=()=>h.open('q');h.click('input_delete',{id:'field'});await flush();await h.open('w');assert.equal(h.draft().definition.nodes.j.inputs.length,1);assert.equal(h.writes.length,0);});
test('version history displays the exact stored publisher safely',async()=>{const h=harness();h.workflows.get('w').versions=[{version:1,publisher:'user:<native-id>',published_at:'2026-10-02',hash:'saved-hash'}];h.render();h.click('tab',{tab:'history'});await flush();assert.match(h.markup,/user:&lt;native-id&gt;/);assert.doesNotMatch(h.markup,/<native-id>/);});

test('AI composer snapshots physical expansion and live text before a delayed model-list repaint',async()=>{const h=harness(),listing=deferred();h.designer.reset();h.modelsOverride=()=>listing.promise;h.render();assert.equal(h.composer.open,false);h.composer.open=true;h.fields.find(field=>field.name==='ai_prompt').value='그리는 도중 입력한 개인 초안';listing.resolve({models:[{id:'m',name:'현재 Native 모델'}]});await flush();assert.equal(h.composer.open,true);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'그리는 도중 입력한 개인 초안');h.click('ai_propose');await flush();assert.equal(h.proposals[0].prompt,'그리는 도중 입력한 개인 초안');assert.equal(h.writes.length,0);});
test('routine workspace polls preserve the user-open composer and retain an explicitly closed composer',async()=>{const h=harness();await flush();h.composer.open=true;h.fields.find(field=>field.name==='ai_prompt').value='poll 전 작성';for(let i=0;i<3;i++)h.render();assert.equal(h.composer.open,true);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'poll 전 작성');h.composer.open=false;h.render();assert.equal(h.composer.open,false);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'poll 전 작성');assert.equal(h.draft().dirty,false);assert.equal(h.proposals.length,0);assert.equal(h.writes.length,0);});
test('composer text and expansion are private to the workflow and Native conversation and reset on account change',async()=>{const h=harness();await flush();h.composer.open=true;h.field('ai_prompt','A 대화의 W 절차 초안');await h.open('q');assert.equal(h.composer.open,false);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'');await h.open('w');assert.equal(h.composer.open,true);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'A 대화의 W 절차 초안');h.selection.chat_id='other-private-chat';h.render();assert.equal(h.composer.open,false);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'');h.selection.chat_id='private-chat';h.render();assert.equal(h.composer.open,true);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'A 대화의 W 절차 초안');h.state.capabilities.actor_id='b';h.render();await flush();assert.equal(h.composer.open,false);assert.equal(h.fields.find(field=>field.name==='ai_prompt').value,'');assert.doesNotMatch(h.markup,/A 대화의 W 절차 초안/);});
test('a pending right-composer response is discarded after a conversation switch even if transport ignores abort',async()=>{const h=harness(),pending=deferred();await flush();h.proposeOverride=()=>pending.promise;h.composer.open=true;h.field('ai_prompt','원래 대화 요청');h.click('ai_propose');await flush();const request=h.proposals[0];h.selection.chat_id='different-chat';h.render();assert.equal(request.signal.aborted,true);pending.resolve({workflow_id:'w',base_revision:1,context_id:request.context_id,definition:{...definition(),name:'이전 대화 응답'}});await flush();assert.equal(h.composer.open,false);assert.equal(h.buttons.some(button=>button.dataset.authorAction==='ai_apply'),false);assert.doesNotMatch(h.markup,/이전 대화 응답/);assert.equal(h.draft().definition.name,'절차 w');assert.equal(h.writes.length,0);});

test('B2-2 rules are scoped to eligible jobs and preserve stored judgment IDs and legacy defaults',async()=>{
 const h=harness(),record=h.workflows.get('w'),global=[{id:'approved-old',label:'통과',status:'completed'}];record.draft.judgments=global;
 record.draft.nodes.j.result_block='item_verdict';record.draft.nodes.k={...copy(record.draft.nodes.j),id:'k',name:'별도 판정',result_block:'checklist'};
 h.render();h.click('tab',{tab:'rules'});await flush();assert.equal(h.draft().dirty,false);assert.equal(h.draft().definition.nodes.j.judgments,undefined);
 assert.match(h.markup,/확인 항목 · 항목별 판정/);assert.doesNotMatch(h.markup,/CR별 승인|개발 설계서|조건부 승인/);
 h.dialogs.push({label:'확인 완료',status:'completed',consequence:'다음 작업에서 근거 확인'});h.click('judgment_edit',{id:'0'});await flush();
 assert.deepEqual(h.draft().definition.nodes.j.judgments,[{id:'approved-old',label:'확인 완료',status:'completed',consequence:'다음 작업에서 근거 확인'}]);
 assert.deepEqual(h.draft().definition.judgments,global);assert.equal(h.draft().definition.nodes.k.judgments,undefined);
 h.field('rule_job_id','k','change');h.dialogs.push({label:'보완 필요',status:'action_required',consequence:'담당자 확인'});h.click('judgment_add');await flush();
 const k=h.draft().definition.nodes.k;assert.equal(k.judgments.length,2);assert.equal(k.judgments[0].id,'approved-old');assert.equal(h.draft().definition.nodes.j.judgments.length,1);
 assert.equal(h.writes.length,0);h.click('save');await flush();assert.equal(h.writes[0].definition.nodes.k.judgments[1].label,'보완 필요');
});
test('B2-2 suggestion rules save guidance and human-only IDs without auto-confirmation or reference replacement',async()=>{
 const h=harness(),record=h.workflows.get('w');record.draft.nodes.j.result_block='item_verdict';record.draft.nodes.j.judgments=[{id:'ok',label:'승인',status:'completed'},{id:'human',label:'보완 후 확인',status:'action_required'}];
 h.render();h.click('tab',{tab:'rules'});await flush();h.field('suggestion_description','현재 입력에서 확인한 필수 조건');h.field('human_only:human',true,'change');
 h.dialogs.push({condition:'근거가 충분하지 않으면',judgment_id:''});h.click('suggestion_add');await flush();
 h.dialogs.push({condition:'근거가 충족되면',judgment_id:'ok'});h.click('suggestion_add');await flush();
 const node=h.draft().definition.nodes.j;assert.equal(node.suggestion_rules.provisional,true);assert.deepEqual(node.suggestion_rules.human_only_judgment_ids,['human']);
 assert.deepEqual(node.suggestion_rules.rules.map(rule=>[rule.condition,rule.outcome,rule.judgment_id]),[['근거가 충분하지 않으면','none',''],['근거가 충족되면','judgment','ok']]);
 assert.doesNotMatch(h.dialogHistory.at(-1).html,/<option value="human"/);assert.equal(node.human_confirmation,true);assert.equal(h.writes.length,0);
 h.field('confirmation_notes','확정 뒤에는 근거를 다시 확인');h.click('save');await flush();assert.equal(h.writes[0].definition.nodes.j.confirmation_notes,'확정 뒤에는 근거를 다시 확인');
});
test('B2-2 a job switch while its dialog is open cannot edit a different job',async()=>{
 const h=harness(),record=h.workflows.get('w');record.draft.nodes.j.result_block='checklist';record.draft.nodes.k={...copy(record.draft.nodes.j),id:'k',name:'다른 작업'};
 h.render();h.click('tab',{tab:'rules'});await flush();h.dialogs.push({label:'이전 화면의 변경',status:'failed'});h.dialogHook=()=>h.field('rule_job_id','k','change');h.click('judgment_add');await flush();
 assert.equal(h.draft().definition.nodes.j.judgments,undefined);assert.equal(h.draft().definition.nodes.k.judgments,undefined);assert.equal(h.draft().dirty,false);
});
test('B2-3 advisories do not block publication while blockers remain visible and disabled',async()=>{
 const h=harness(),record=h.workflows.get('w');h.writeOverride=async body=>{if(body.action==='validate_workflow'){record.validation={revision:1,checked_at:'2026-10-05T08:00:00Z',errors:[],warnings:['j: 송부 방식이 정해지지 않았습니다'],checks:['결과 형태 확인']};return {ok:true,validation:copy(record.validation)};}return {ok:true};};
 h.click('validate');await flush();assert.match(h.markup,/게시를 막는 문제 0/);assert.match(h.markup,/확인 권장 1/);assert.match(h.markup,/통과 1/);assert.match(h.markup,/2026-10-05T08:00:00Z/);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='publish').disabled,false);
 h.click('validation_open',{id:'warnings:0'});await flush();assert.match(h.markup,/ew-author-rule-policy/);
 h.writeOverride=async()=>{record.validation={revision:1,errors:['j: 결과 형태 없음'],warnings:[],checks:[]};return {ok:true,validation:copy(record.validation)};};h.click('validate');await flush();assert.match(h.markup,/게시를 막는 문제 1/);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='publish').disabled,true);
 h.click('publish');await flush();assert.equal(h.writes.filter(body=>body.action==='publish_workflow').length,0);h.click('validation_open',{id:'errors:0'});await flush();assert.match(h.markup,/id="ew-author-node"/);
});
test('B5 direct execution stores only declared exception metadata and retains absent adapter reason',async()=>{
 const h=harness();h.selection.tab='tools';h.state.native_users=[{id:'owner',name:'시스템 담당자'}];h.state.reviewers=[{id:'owner',name:'시스템 담당자'}];h.state.can_author_direct=true;h.render();await h.example('restart-service');h.click('tool_direct');await flush();
 assert.match(h.markup,/직접 실행 · 예외/);assert.match(h.markup,/실행 주체는 EES Work/);assert.match(h.markup,/허용된 실행 연결이 없으면 실제 동작은 차단/);
 h.field('name','담당자 소유 예외');h.field('exception:api_unavailable_reason','담당자 검토에서 API 제공 불가 확인');h.field('exception:owner_user_id','owner','change');h.field('exception:allowed_commands','approved-command-1\napproved-command-2');h.field('exception:account_reference','dedicated-account');h.field('exception:least_privilege',true,'change');h.field('responsible_user_id','owner','change');h.click('tool_save');await flush();
 const tool=h.operations[0].tool;assert.equal(tool.kind,'direct');assert.deepEqual(tool.exception_contract,{api_unavailable_reason:'담당자 검토에서 API 제공 불가 확인',owner_user_id:'owner',allowed_commands:['approved-command-1','approved-command-2'],account_reference:'dedicated-account',least_privilege:true});assert.equal(Object.keys(tool).some(key=>key.startsWith('exception:')),false);assert.equal(tool.reference,undefined);assert.equal(h.operations.some(body=>body.action.includes('execute')),false);
});
test('C12 schedule opening and explicit execution scope do not alter preserved drafts on inspection',async()=>{
 const h=harness();h.workflows.get('w').draft.nodes.j.execution_scope='opaque-user-value';h.render();await h.node();assert.doesNotMatch(h.markup,/name="execution_scope"/);assert.equal(h.draft().definition.execution_scope,undefined);h.dialogs.push({name:'절차 w',category:'ops',execution_scope:'system',description:''});h.click('edit_workflow');await flush();assert.equal(h.draft().definition.execution_scope,'system');assert.equal(h.draft().definition.nodes.j.execution_scope,'opaque-user-value');h.dialogs.push({name:'절차 w',category:'ops',execution_scope:'',description:''});h.click('edit_workflow');await flush();assert.equal(h.draft().definition.execution_scope,undefined);
 h.click('tab',{tab:'schedule'});h.click('run_mode',{id:'periodic'});await flush();assert.match(h.markup,/직전 회차가 남아도 일정대로 열림/);h.field('opening','on_schedule','change');assert.equal(h.draft().definition.schedule.opening,'on_schedule');
});

test('B5 direct classification selects registered Native metadata without configuring execution',async()=>{
 const h=harness(),reference={tool_id:'registered',function:'permitted',content_hash:'current'},schema={type:'object',properties:{target:{type:'string'}}};h.selection.tab='tools';h.state.can_author_direct=true;h.state.native_functions=[{kind:'request',name:'등록 기능',reference,schema},nativeFunction('registered','상태 조회','request','observed_status')];h.render();await h.pick('registered:permitted');h.click('tool_direct');await flush();h.field('status_function','observed_status','change');h.click('tool_save');await flush();const tool=h.operations[0].tool;assert.equal(tool.kind,'direct');assert.deepEqual(tool.reference,reference);assert.deepEqual(tool.input_schema,schema);assert.equal(tool.status_function,'observed_status');assert.match(h.markup,/기능을 선택해도 직접 실행 연결은 구성되지 않습니다/);assert.doesNotMatch(h.markup,/name="input_schema/);
});


// Simulate the missing API on intranet HTTP; these remain synthetic DOM tests.
const uuidV4=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const httpCrypto=()=>({getRandomValues:bytes=>crypto.webcrypto.getRandomValues(bytes)});
test('missing randomUUID permits create and authoring IDs through the shared helper',async()=>{
 const h=harness({cryptoProvider:httpCrypto()});await flush();
 h.click('create');await flush();await h.chooseTemplate('blank');h.field('ew-procedure-name','HTTP 새 절차');h.click('procedure_create');await flush();assert.equal(h.writes[0].action,'create_workflow');assert.match(h.writes[0].request_id,uuidV4);
 assert.equal(h.writes[0].name,'HTTP 새 절차');assert.equal(h.writes[0].expected_revision,0);
 h.click('add_stage');await flush();const stage=Object.values(h.draft().definition.nodes).find(node=>node.id.startsWith('stage-'));
 assert.match(stage.id.slice(6),uuidV4);h.click('add_job',{parent:stage.id});await flush();
 const job=Object.values(h.draft().definition.nodes).find(node=>node.id.startsWith('job-'));assert.match(job.id.slice(4),uuidV4);
 const answer={name:'대상 서버',type:'text',scope:'run',options_source:'manual'};
 h.dialogHook=()=>{answer.id=controls(h.dialogHistory.at(-1).html).find(field=>field.name==='id').value;};
 h.dialogs.push(answer);h.click('input_add');await flush();h.dialogHook=null;
 const field=h.draft().definition.nodes[job.id].inputs[0];assert.match(field.id.slice(6),uuidV4);
 h.field('result_block','item_verdict','change');h.click('tab',{tab:'rules'});await flush();
 h.dialogs.push({label:'확인 완료',status:'completed',consequence:'근거 확인'});h.click('judgment_add');await flush();
 const judgment=h.draft().definition.nodes[job.id].judgments.find(value=>value.id.startsWith('judgment-'));assert.match(judgment.id.slice(9),uuidV4);
 h.dialogs.push({condition:'근거가 확인되면',judgment_id:judgment.id});h.click('suggestion_add');await flush();
 const rule=h.draft().definition.nodes[job.id].suggestion_rules.rules[0];assert.match(rule.id.slice(5),uuidV4);
 h.click('save');await flush();const saved=h.writes.at(-1);assert.equal(saved.action,'save_draft');assert.match(saved.request_id,uuidV4);
 assert.equal(saved.definition.nodes[job.id].parent,stage.id);assert.equal(saved.definition.nodes[job.id].inputs[0].id,field.id);
 assert.equal(saved.definition.nodes[job.id].suggestion_rules.rules[0].judgment_id,judgment.id);
 const ids=[h.writes[0].request_id,stage.id.slice(6),job.id.slice(4),field.id.slice(6),judgment.id.slice(9),rule.id.slice(5),saved.request_id];
 assert.equal(new Set(ids).size,ids.length);assert.equal(h.workflows.get('w').published_version,null);
});
test('missing randomUUID keeps authoring retries idempotent and changed edits distinct',async()=>{
 const h=harness({cryptoProvider:httpCrypto()});await h.node();h.writeOverride=async()=>{throw new Error('response lost');};
 h.field('instructions','재시도할 초안');h.click('save');await flush();h.click('save');await flush();
 assert.match(h.writes[0].request_id,uuidV4);assert.deepEqual(h.writes[1],h.writes[0]);
 h.field('instructions','바뀐 초안');h.click('save');await flush();assert.match(h.writes[2].request_id,uuidV4);
 assert.notEqual(h.writes[2].request_id,h.writes[0].request_id);assert.equal(h.draft().definition.nodes.j.instructions,'바뀐 초안');
});
test('missing randomUUID keeps AI proposal context and explicit apply without saving',async()=>{
 const h=harness({cryptoProvider:httpCrypto()});await flush();h.field('ai_prompt','업무 절차를 설명해 줘');h.click('ai_propose');await flush();
 assert.equal(h.proposals.length,1);assert.match(h.proposals[0].context_id,uuidV4);assert.equal(h.proposals[0].workflow_id,'w');
 assert.equal(h.draft().definition.name,'절차 w');assert.equal(h.writes.length,0);
 h.click('ai_apply');await flush();assert.equal(h.draft().definition.name,'AI 제안');assert.equal(h.draft().dirty,true);assert.equal(h.writes.length,0);
});


test('easy tool starter groups live connections and searches names without creating a contract',async()=>{
 const h=harness();h.selection.tab='tools';h.state.native_functions=[nativeFunction('jira','CR 승인 상태 조회','read','jira_search_crs'),nativeFunction('jira','프로젝트 조회','read','jira_project_metadata'),nativeFunction('ops','재시작 요청','request','restart_service')];h.render();h.click('tool_create');await flush();
 assert.match(h.markup,/예시에서 시작/);assert.match(h.markup,/연결된 기능에서 고르기/);assert.match(h.markup,/연결된 Jira/);assert.match(h.markup,/jira:jira_search_crs/);assert.match(h.markup,/정보 읽기/);assert.match(h.markup,/EES에 작업 부탁/);
 assert.equal(h.buttons.filter(button=>button.dataset.authorAction==='tool_example').length,4);assert.equal(h.buttons.filter(button=>button.dataset.authorAction==='tool_pick').length,3);assert.equal(h.fields.some(field=>field.name==='name'),false);assert.equal(h.operations.length,0);
 h.field('ew-tool-search','승인');await flush();assert.deepEqual(h.buttons.filter(button=>button.dataset.authorAction==='tool_pick').map(button=>button.dataset.id),['jira:jira_search_crs']);assert.equal(h.operations.length,0);
});
test('tool examples resolve current connections anew and EMS read examples remain unconnected',async()=>{
 const h=harness();h.selection.tab='tools';h.state.native_functions=[nativeFunction('jira','CR 조회','read','jira_search_crs'),nativeFunction('ems','상태 조회','request','service_status')];h.render();await h.example('jira-query');h.click('tool_save');await flush();
 assert.equal(h.operations[0].tool.name,'Jira 조회');assert.equal(h.operations[0].tool.kind,'read');assert.deepEqual(h.operations[0].tool.reference,h.state.native_functions[0].reference);assert.equal(h.operations[0].tool.id,undefined);
 h.click('tool_list');await flush();h.state.native_functions=[];h.render();await h.example('jira-query');h.click('tool_save');await flush();assert.equal(h.operations[1].tool.reference,undefined);assert.equal(h.operations[1].tool.id,undefined);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,true);assert.match(h.markup,/필요한 기능이 아직 연결되지 않았습니다/);h.click('tool_review');await flush();assert.equal(h.operations.length,2);
 h.click('tool_list');await flush();h.state.native_functions=[nativeFunction('ems','상태 조회','read','service_status')];h.render();await h.example('service-status');h.click('tool_save');await flush();assert.equal(h.operations[2].tool.reference,undefined);assert.equal(h.operations[2].tool.kind,'read');assert.match(h.markup,/필요한 기능이 아직 연결되지 않았습니다/);assert.equal(h.writes.length,0);
});
test('choosing a live function determines kind and new output contracts are never fabricated',async()=>{
 for(const kind of ['read','request']){const h=harness();h.selection.tab='tools';h.state.native_functions=[nativeFunction('registered','현재 기능',kind,'current')];h.render();await h.pick('registered:current');assert.equal(h.fields.some(field=>field.name==='kind'),false);assert.equal(h.fields.find(field=>field.name==='output_schema_json').value,'');assert.match(h.markup,/고급 · 개발자용/);assert.doesNotMatch(h.markup,/<details[^>]*open[^>]*>[\s\S]*결과 형식/);h.click('tool_save');await flush();assert.equal(h.operations[0].tool.kind,kind);assert.equal(h.operations[0].tool.output_schema,undefined);}
});
test('removed time fields remain opaque and survive unrelated read and request resaves',async()=>{
 for(const kind of ['read','request']){const h=harness(),fn=nativeFunction('registered','현재 기능',kind,'current');h.selection.tab='tools';h.state.native_functions=[fn];h.state.tools=[{id:'legacy',name:'기존 도구',kind,reference:fn.reference,input_schema:fn.schema,revision:9,state:'draft',timeout_seconds:37,completion_wait_seconds:642,output_schema:{type:'object',properties:{kept:{type:'string'}}}}];h.render();h.click('tool_open',{id:'legacy'});await flush();assert.equal(h.fields.some(field=>['timeout_seconds','completion_wait_seconds','kind'].includes(field.name)),false);h.field('description','설명만 수정');h.click('tool_save');await flush();assert.equal(h.operations[0].tool.timeout_seconds,37);assert.equal(h.operations[0].tool.completion_wait_seconds,642);assert.equal(h.operations[0].expected_revision,9);assert.deepEqual(h.operations[0].tool.output_schema,{type:'object',properties:{kept:{type:'string'}}});}
});
test('request state choices stay within the connected tool and sole reviewer and state function are preselected',async()=>{
 const h=harness();h.selection.tab='tools';h.state.reviewers=[{id:'owner',name:'EES 담당자'}];h.state.native_functions=[nativeFunction('ops','재시작','request','restart_service'),nativeFunction('ops','재시작 상태','request','restart_status'),nativeFunction('unrelated','다른 상태','request','other_status')];h.render();await h.pick('ops:restart_service');assert.equal(h.fields.find(field=>field.name==='status_function').value,'restart_status');assert.doesNotMatch(h.markup,/<option value="other_status"/);assert.doesNotMatch(h.markup,/<option value="restart_service"/);h.click('tool_save');await flush();assert.equal(h.operations[0].tool.status_function,'restart_status');assert.equal(h.operations[0].tool.responsible_user_id,'owner');assert.equal(h.operations[0].tool.output_schema,undefined);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,true);h.field('guide_url','https://example.invalid/guide');h.click('tool_save');await flush();assert.match(h.markup,/결과 형식이 비어 있습니다/);assert.match(h.markup,/담당자나 개발자/);h.click('tool_review');await flush();assert.equal(h.operations.length,2);
});
test('multiple request state functions and reviewers require a choice and changing a function preserves authored text',async()=>{
 const h=harness();h.selection.tab='tools';h.state.reviewers=[{id:'first',name:'첫 담당자'},{id:'second',name:'둘째 담당자'}];h.state.native_functions=[nativeFunction('ops','재시작','request','restart_service'),nativeFunction('ops','상태1','request','status_one'),nativeFunction('ops','상태2','request','status_two'),nativeFunction('jira','CR 조회','read','jira_search_crs')];h.render();await h.pick('ops:restart_service');assert.equal(h.fields.find(field=>field.name==='status_function').value,'');assert.equal(h.fields.find(field=>field.name==='responsible_user_id').value,'');h.field('name','내가 쓴 도구');h.field('description','내가 쓴 설명');h.click('tool_change');await flush();h.click('tool_pick',{id:'jira:jira_search_crs'});await flush();h.click('tool_save');await flush();assert.equal(h.operations[0].tool.kind,'read');assert.equal(h.operations[0].tool.name,'내가 쓴 도구');assert.equal(h.operations[0].tool.description,'내가 쓴 설명');assert.equal(h.operations[0].tool.status_function,undefined);assert.equal(h.fields.some(field=>field.name==='responsible_user_id'),false);
});
test('read confirmation is allowed after save without a guide and explicit next step clears when complete',async()=>{
 const h=harness();h.selection.tab='tools';h.state.native_functions=[nativeFunction('jira','CR 조회','read','jira_search_crs')];h.render();await h.pick('jira:jira_search_crs');assert.match(h.markup,/초안을 먼저 저장/);assert.equal(h.fields.some(field=>field.name==='responsible_user_id'),false);h.click('tool_save');await flush();assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,false);h.click('tool_review');await flush();assert.equal(h.operations.at(-1).action,'tool_submit');assert.equal(h.operations.at(-1).tool_contract_id,'tool');assert.equal(h.operations[0].tool.guide_url || '','');
});
test('direct exception creation is hidden and inert without an eligible reviewer capability',async()=>{
 for(const allowed of [false,true]){const h=harness();h.selection.tab='tools';h.state.can_author_direct=allowed;h.render();await h.example('restart-service');assert.equal(h.buttons.some(button=>button.dataset.authorAction==='tool_direct'),allowed);h.click('tool_direct');await flush();if(allowed){assert.match(h.markup,/직접 실행 · 예외/);assert.ok(h.fields.some(field=>field.name==='exception:api_unavailable_reason'));}else{assert.equal(h.fields.some(field=>field.name==='exception:api_unavailable_reason'),false);assert.equal(h.operations.length,0);}}
});
test('unconnected examples still save with missing randomUUID but never submit or execute',async()=>{
 const h=harness({cryptoProvider:httpCrypto()});h.selection.tab='tools';h.render();await h.example('collection-queue');h.click('tool_save');await flush();assert.match(h.operations[0].request_id,uuidV4);assert.equal(h.operations[0].tool.kind,'read');assert.equal(h.operations[0].tool.reference,undefined);h.click('tool_review');await flush();assert.equal(h.operations.length,1);assert.match(h.markup,/필요한 기능이 아직 연결되지 않았습니다/);
});


test('tool drafts are private to actor and system and return without crossing the selected system',async()=>{
 const h=harness();h.selection.tab='tools';h.render();await h.example('jira-query');h.field('name','EMS 개인 도구');h.field('description','EMS에 남길 개인 초안');
 h.selection.system_id='MES';h.render();assert.doesNotMatch(h.markup,/EMS 개인 도구|EMS에 남길 개인 초안/);await h.example('restart-service');h.field('name','MES 개인 도구');h.field('description','MES에 남길 개인 초안');
 h.selection.system_id='EMS';h.render();assert.equal(h.fields.find(field=>field.name==='name').value,'EMS 개인 도구');assert.equal(h.fields.find(field=>field.name==='description').value,'EMS에 남길 개인 초안');h.click('tool_save');await flush();assert.equal(h.operations[0].tool.system_id,'EMS');assert.equal(h.operations[0].tool.name,'EMS 개인 도구');
 h.state.capabilities.actor_id='different-user';h.render();assert.doesNotMatch(h.markup,/EMS 개인 도구|MES 개인 도구|개인 초안/);h.selection.system_id='MES';h.render();assert.doesNotMatch(h.markup,/EMS 개인 도구|MES 개인 도구|개인 초안/);
});
test('tool save acknowledges its revision and keeps edits typed while the save is pending',async()=>{
 const h=harness(),pending=deferred();h.selection.tab='tools';h.state.native_functions=[nativeFunction('jira','CR 조회','read','jira_search_crs')];h.render();await h.pick('jira:jira_search_crs');h.field('description','보낸 설명');h.operationOverride=()=>pending.promise;h.click('tool_save');await flush();const submitted=h.operations[0];h.field('description','저장 중 새로 입력한 설명');pending.resolve({ok:true,tool:{...submitted.tool,id:'saved-tool',state:'draft',revision:1}});await flush();assert.equal(h.fields.find(field=>field.name==='description').value,'저장 중 새로 입력한 설명');assert.match(h.markup,/저장 안 됨/);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,true);
 h.operationOverride=async body=>({ok:true,tool:{...body.tool,id:'saved-tool',state:'draft',revision:2}});h.click('tool_save');await flush();assert.equal(h.operations[1].expected_revision,1);assert.equal(h.operations[1].tool.id,'saved-tool');assert.equal(h.operations[1].tool.description,'저장 중 새로 입력한 설명');assert.equal(h.operations[0].tool.description,'보낸 설명');
});
test('late tool save cannot replace a different tool opened during the request',async()=>{
 const h=harness(),pending=deferred(),fn=nativeFunction('jira','CR 조회','read','jira_search_crs');h.selection.tab='tools';h.state.native_functions=[fn];h.state.tools=[{id:'first',name:'첫 도구',kind:'read',system_id:'EMS',reference:fn.reference,input_schema:fn.schema,revision:1,state:'draft'},{id:'second',name:'두 번째 도구',kind:'read',system_id:'EMS',reference:fn.reference,input_schema:fn.schema,revision:7,state:'draft'}];h.render();h.click('tool_open',{id:'first'});await flush();h.field('description','첫 도구 저장 요청');h.operationOverride=()=>pending.promise;h.click('tool_save');await flush();const submitted=h.operations[0];h.click('tool_list');h.click('tool_open',{id:'second'});await flush();assert.equal(h.fields.find(field=>field.name==='name').value,'두 번째 도구');pending.resolve({ok:true,tool:{...submitted.tool,revision:2}});await flush();assert.equal(h.fields.find(field=>field.name==='name').value,'두 번째 도구');h.operationOverride=async body=>({ok:true,tool:{...body.tool,revision:8}});h.field('description','다음 도구 수정');h.click('tool_save');await flush();assert.equal(h.operations[1].tool.id,'second');assert.equal(h.operations[1].expected_revision,7);assert.equal(h.operations[1].tool.description,'다음 도구 수정');
});


test('legacy direct metadata survives an ordinary author resave while exception controls remain hidden',async()=>{
 const h=harness(),fn=nativeFunction('legacy','기존 예외 연결','request','execute'),exception={api_unavailable_reason:'검토한 사유',owner_user_id:'owner',allowed_commands:['reviewed-command'],account_reference:'dedicated-account',least_privilege:true};h.selection.tab='tools';h.state.native_functions=[fn];h.state.tools=[{id:'legacy-direct',name:'기존 예외',kind:'direct',system_id:'EMS',state:'draft',revision:4,reference:fn.reference,input_schema:fn.schema,exception_contract:exception}];h.state.can_author_direct=false;h.render();h.click('tool_open',{id:'legacy-direct'});await flush();assert.equal(h.fields.some(field=>field.name.startsWith('exception:')),false);assert.equal(h.buttons.some(button=>['tool_direct','tool_request'].includes(button.dataset.authorAction)),false);h.field('description','설명만 변경');h.click('tool_save');await flush();assert.equal(h.operations[0].tool.kind,'direct');assert.deepEqual(h.operations[0].tool.exception_contract,exception);assert.deepEqual(h.operations[0].tool.reference,fn.reference);
});
test('direct function replacement lists only request functions and rejects a forged read selection',async()=>{
 const h=harness(),current=nativeFunction('ops','기존 예외 연결','request','execute'),next=nativeFunction('new-ops','새 예외 연결','request','execute_next'),read=nativeFunction('jira','조회','read','jira_search_crs');h.selection.tab='tools';h.state.can_author_direct=true;h.state.native_functions=[current,next,read];h.state.tools=[{id:'direct',name:'예외',kind:'direct',system_id:'EMS',state:'draft',revision:5,reference:current.reference,input_schema:current.schema}];h.render();h.click('tool_open',{id:'direct'});await flush();h.click('tool_change');await flush();assert.deepEqual(h.buttons.filter(button=>button.dataset.authorAction==='tool_pick').map(button=>button.dataset.id),['ops:execute','new-ops:execute_next']);h.click('tool_pick',{id:'jira:jira_search_crs'});await flush();assert.match(h.markup,/연결된 기능에서 고르기/);assert.equal(h.operations.length,0);h.click('tool_pick',{id:'new-ops:execute_next'});await flush();h.click('tool_save');await flush();assert.equal(h.operations[0].tool.kind,'direct');assert.deepEqual(h.operations[0].tool.reference,next.reference);assert.deepEqual(h.operations[0].tool.input_schema,next.schema);
});

test('server tool validation errors explain the next action and preserve the editable draft',async()=>{
 for(const [code,message] of [['guide_required',/가이드 문서.*주소를 입력/],['request_output_schema_invalid',/담당자나 개발자/],['native_version_changed',/바꾸기에서 기능을 다시 고르/]]){const h=harness();h.selection.tab='tools';h.state.native_functions=[nativeFunction('jira','CR 조회','read','jira_search_crs')];h.render();await h.pick('jira:jira_search_crs');h.field('description','서버 거부 뒤에도 보존할 설명');h.operationOverride=async()=>({ok:false,error:{code,message:'internal_tool_diagnostic'}});h.click('tool_save');await flush();assert.match(h.markup,message);assert.doesNotMatch(h.markup,/internal_tool_diagnostic/);assert.equal(h.fields.find(field=>field.name==='description').value,'서버 거부 뒤에도 보존할 설명');assert.equal(h.operations.length,1);assert.equal(h.buttons.find(button=>button.dataset.authorAction==='tool_review').disabled,true);}
});

test('new procedure opens three summarized examples and a blank choice without creating or exposing definition controls',async()=>{
 const h=harness();h.click('create');await flush();assert.match(h.markup,/ew-procedure-start/);assert.equal(h.fields.filter(field=>field.name==='procedure_template').length,4);assert.equal(h.fields.find(field=>field.name==='procedure_template'&&field.checked).value,'factory_rollout');assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'신규 공장 횡전개');assert.equal(h.writes.length,0);
 for(const example of procedureExamples){await h.chooseTemplate(example.id);assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,example.name);for(const stage of example.stages)assert.ok(h.markup.includes(stage.name));assert.match(h.markup,new RegExp('단계\\s*'+example.stage_count+'\\s*·\\s*작업\\s*'+example.job_count));assert.doesNotMatch(h.markup,/name="(?:category|mode|run_mode|execution_scope)"/);assert.equal(h.writes.length,0);}
});
test('example start submits only the selected server template and edited name and opens the acknowledged draft',async()=>{
 const h=harness();h.state.procedure_examples[1].definition={name:'untrusted-client-definition',nodes:{injected:{}}};h.click('create');await flush();h.field('ew-procedure-name','우리 공장 횡전개');h.click('procedure_create');await flush();assert.equal(h.writes.length,1);const body=h.writes[0];assert.equal(body.action,'create_workflow');assert.equal(body.template_id,'factory_rollout');assert.equal(body.name,'우리 공장 횡전개');assert.equal(body.system_id,'EMS');assert.equal(body.expected_revision,0);assert.equal(body.definition,undefined);assert.equal(body.schedule,undefined);assert.equal(body.category,undefined);assert.equal(body.mode,undefined);assert.equal(body.execution_scope,undefined);assert.equal(h.selection.workflow_id,'created-1');assert.doesNotMatch(h.markup,/ew-procedure-start/);assert.equal(h.draft().definition.name,'우리 공장 횡전개');assert.equal(h.operations.length,0);
});
test('blank start asks only for a name and leaves defaults to the server',async()=>{
 const h=harness();h.click('create');await flush();await h.chooseTemplate('blank');assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'');h.click('procedure_create');await flush();assert.equal(h.writes.length,0);h.field('ew-procedure-name','  빈 절차  ');h.click('procedure_create');await flush();const body=h.writes[0];assert.equal(body.name,'빈 절차');for(const field of ['template_id','definition','category','mode','execution_scope','schedule'])assert.equal(Object.hasOwn(body,field),false,field);assert.equal(body.expected_revision,0);assert.equal(h.operations.length,0);
});
test('starter cancellation reentry and system navigation preserve separate selected examples and names without writing',async()=>{
 const h=harness(),before=h.draft();h.click('create');await flush();h.field('ew-procedure-name','EMS 횡전개 이름');await h.chooseTemplate('daily_check');h.field('ew-procedure-name','EMS 일일 이름');h.click('procedure_cancel');await flush();assert.doesNotMatch(h.markup,/ew-procedure-start/);await h.open('w');assert.deepEqual(h.draft(),before);h.click('create');await flush();assert.equal(h.fields.find(field=>field.name==='procedure_template'&&field.checked).value,'daily_check');assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'EMS 일일 이름');await h.chooseTemplate('factory_rollout');assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'EMS 횡전개 이름');
 h.selection.system_id='MES';h.render();assert.doesNotMatch(h.markup,/EMS 횡전개 이름|EMS 일일 이름/);h.click('create');await flush();h.field('ew-procedure-name','MES 횡전개 이름');h.selection.system_id='EMS';h.render();h.click('create');await flush();assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'EMS 횡전개 이름');h.state.capabilities.actor_id='other-user';h.render();h.click('create');await flush();assert.doesNotMatch(h.markup,/EMS 횡전개 이름|EMS 일일 이름|MES 횡전개 이름/);assert.equal(h.writes.length,0);
});
test('failed creation retries one request while successful repeated starts use different request IDs',async()=>{
 const h=harness({cryptoProvider:httpCrypto()});h.click('create');await flush();h.field('ew-procedure-name','반복 생성 이름');h.writeOverride=async()=>{throw new Error('응답을 받지 못했습니다');};h.click('procedure_create');await flush();h.click('procedure_create');await flush();assert.equal(h.writes.length,2);assert.deepEqual(h.writes[0],h.writes[1]);assert.match(h.writes[0].request_id,uuidV4);assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'반복 생성 이름');
 h.writeOverride=null;h.click('procedure_create');await flush();assert.equal(h.writes[2].request_id,h.writes[0].request_id);h.click('create');await flush();await h.chooseTemplate('factory_rollout');h.field('ew-procedure-name','반복 생성 이름');h.click('procedure_create');await flush();assert.notEqual(h.writes[3].request_id,h.writes[2].request_id);assert.match(h.writes[3].request_id,uuidV4);assert.equal(h.writes[3].template_id,h.writes[2].template_id);assert.equal(h.writes[3].name,h.writes[2].name);assert.equal(h.selection.workflow_id,'created-4');
});
test('late creation cannot replace a changed or reopened starter or a different system',async()=>{
 for(const change of ['name','cancel','system']){const h=harness(),pending=deferred();h.click('create');await flush();h.field('ew-procedure-name','전송한 이름');h.writeOverride=()=>pending.promise;h.click('procedure_create');await flush();assert.equal(h.writes.length,1);if(change==='name')h.field('ew-procedure-name','응답 대기 중 새 이름');if(change==='cancel'){h.designer.closeStart();h.render();h.click('create');await flush();}if(change==='system'){h.selection.system_id='MES';h.render();h.click('create');await flush();h.field('ew-procedure-name','MES 새 이름');}
  const draft=definition('late-created');draft.name='전송한 이름';draft.system_id='EMS';const record={id:'late-created',name:'전송한 이름',system_id:'EMS',revision:1,can_manage:true,published_version:null,draft};h.workflows.set(record.id,record);pending.resolve({ok:true,workflow_id:record.id,revision:1,workflow:copy(record)});await flush();assert.equal(h.selection.workflow_id,'',change);assert.match(h.markup,/ew-procedure-start/,change);if(change==='name')assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'응답 대기 중 새 이름');if(change==='system')assert.equal(h.fields.find(field=>field.id==='ew-procedure-name').value,'MES 새 이름');assert.equal(h.operations.length,0);
 }
});

test('procedure creation disables template name and cancel controls until its response',async()=>{
 const h=harness(),pending=deferred();h.click('create');await flush();h.writeOverride=()=>pending.promise;h.click('procedure_create');await flush();assert.ok(h.fields.filter(field=>field.name==='procedure_template'||field.id==='ew-procedure-name').every(field=>field.disabled));assert.ok(h.buttons.filter(button=>['procedure_create','procedure_cancel'].includes(button.dataset.authorAction)).every(button=>button.disabled));await h.chooseTemplate('daily_check');assert.equal(h.designer.readStartContext().templateId,'factory_rollout');
 pending.resolve({ok:false,error:{code:'invalid_definition',message:'예시를 확인해 주세요.'}});await flush();assert.equal(h.fields.find(field=>field.name==='procedure_template'&&field.checked).value,'factory_rollout');assert.ok(h.fields.filter(field=>field.name==='procedure_template'||field.id==='ew-procedure-name').every(field=>!field.disabled));assert.equal(h.buttons.find(button=>button.dataset.authorAction==='procedure_cancel').disabled,false);assert.match(h.markup,/예시를 확인해 주세요/);
});
