const test=require('node:test'),assert=require('node:assert/strict');
const {renderer,run,controller,deferred}=require('./ees_workspace_ui_fixture.cjs');
function html(source,values={}){const context=renderer(values);return run(context,source);}
test('unknown partial failed and excluded states never render completion',()=>{for(const status of ['unknown','partial','failed','excluded','missed']){const out=html('workStatusHTML(status)',{status});assert.doesNotMatch(out,/>완료</);assert.match(out,new RegExp('data-status="'+status+'"'));}});
test('all eight declared input kinds render typed named accessible controls',()=>{for(const type of ['text','number','datetime','single','multi','list','person','boolean']){const out=html('workInputHTML(field,undefined)',{field:{id:'value',name:'입력',type,required:true,options:['x']}});assert.match(out,/name="value"/);assert.match(out,/required/);assert.match(out,/for="ew-run-value"/);}});
test('boolean false number zero and typed enum values survive input rendering',()=>{assert.match(html('workInputHTML({id:"b",type:"boolean"},false)'),/value="false" selected/);assert.match(html('workInputHTML({id:"n",type:"number"},0)'),/value="0"/);assert.match(html('workInputHTML({id:"s",type:"single",options:[0,false]},false)'),/value="false" selected/);});
test('form reading distinguishes unset from false zero and empty multiselect',()=>{const fields=[['b','boolean','false'],['n','number','0'],['s','single','false'],['empty','text','']].map(([name,type,value])=>({name,value,dataset:{inputType:type}}));fields.push({name:'multi',selectedOptions:[],dataset:{inputType:'multi'}});const value=html('workReadInputs(form)',{form:{querySelectorAll:()=>fields}});assert.equal(value.b,false);assert.equal(value.n,0);assert.equal(value.s,false);assert.equal(value.empty,undefined);assert.equal(value.multi.length,0);});
test('all eight result blocks render from the same job definition contract',()=>{for(const block of ['values','schedule','checklist','list_confirm','item_verdict','ai_review','human_confirm','change_request'])assert.match(html('workResultHTML(job)',{job:{result_block:block}}),new RegExp('data-result-block="'+block+'"'));});
test('untrusted job output and names are escaped and unsafe links omitted',()=>{const out=html('workResultHTML(job,saved)',{job:{result_block:'item_verdict'},saved:{result:{items:[{id:'a',name:'<script>bad</script>',url:'javascript:alert(1)',ai_suggestion:'<img onerror=x>'}]}}});assert.match(out,/&lt;script&gt;/);assert.doesNotMatch(out,/<script|<img onerror|javascript:/);});
test('per-item AI proposal is visibly unconfirmed and requires human verdict',()=>{const out=html('workResultHTML(job,saved)',{job:{result_block:'item_verdict'},saved:{result:{items:[{id:'a',ai_suggestion:'적합'}]}}});assert.match(out,/사람 미확정/);assert.match(out,/data-item-verdict/);assert.match(out,/판정 선택/);});
test('read-only historical result blocks never permit input decisions',()=>{const out=html('workResultHTML(job,saved,{readOnly:true})',{job:{result_block:'list_confirm'},saved:{result:{items:[{id:'a'}]}}});assert.match(out,/data-item-confirm[^>]* disabled/);});
test('evidence presence does not claim attachment content adequacy',()=>{const out=html('workResultHTML(job,saved)',{job:{result_block:'item_verdict'},saved:{result:{items:[{id:'a',evidence:[{status:'completed',name:'설계서',content_reviewed:false}]}]}}});assert.match(out,/내용 적정성 미검토/);});
test('request timeline preserves EES report and independent effect confirmation',()=>{const out=html('workRequestHTML(request)',{request:{state:'unknown',events:[{state:'requested',at:'time'}]}});assert.match(out,/완료 보고/);assert.match(out,/효과 확인/);assert.match(out,/자동으로 다시 요청하지 않습니다/);assert.match(out,/data-actor="EES Work"/);assert.match(out,/data-actor="EES"/);});
test('history uses immutable attempt inputs and result rather than current edited values',()=>{const out=html('workHistoryHTML(run)',{run:{version:1,inputs:{secret:'current-input'},attempts:[{id:'one',job_id:'j',number:1,status:'failed',inputs:{a:'historical'},result:{text:'old-result'}}]}});assert.match(out,/historical/);assert.match(out,/old-result/);assert.doesNotMatch(out,/current-input/);});
test('missing history is explicitly unexecuted and never a success fixture',()=>{assert.match(html('workHistoryHTML({attempts:[]})'),/미수행을 성공으로 표시하지 않습니다/);});
test('My Work uses actual tasks and incident-overdue-today-week-future-undated ordering',()=>{const items=['undated','week','overdue','today','future','incident'].map(bucket=>({id:bucket,bucket,name:bucket}));const out=html('workMyWorkHTML(items)',{items});const keys=['incident','overdue','today','week','future','undated'];for(let i=1;i<keys.length;i++)assert.ok(out.indexOf('data-task-id="'+keys[i-1]+'"')<out.indexOf('data-task-id="'+keys[i]+'"'));assert.equal((out.match(/data-action="open_task"/g)||[]).length,6);});
test('empty My Work does not invent an actionable task or normal execution',()=>{const out=html('workMyWorkHTML([])');assert.match(out,/지금 처리할 내 업무가 없습니다/);assert.doesNotMatch(out,/data-task-id|정상 실행/);});
test('late workspace reads are discarded after account change',async()=>{const h=controller(),pending=deferred();h.setReply(()=>pending.promise);const waiting=h.api.refresh();h.setAuth('other-token');pending.resolve({ok:true,private:'actor-a'});await waiting;assert.equal(h.renders.length,0);assert.equal(h.api.snapshot().state,null);});
test('late workspace reads are discarded after selected job changes',async()=>{const h=controller(),pending=deferred();h.setReply(()=>pending.promise);const waiting=h.api.refresh();h.api.setSelection({job_id:'other'});pending.resolve({ok:true,private:'old-job'});await waiting;assert.equal(h.renders.length,0);});
test('lookup failure clears stale private evidence and keeps an explicit read error',async()=>{const h=controller();h.api.setState({run:{private:'old'}});h.setReply(()=>({ok:false,error:{message:'access denied'},httpError:true,status:403}));await h.api.refresh();assert.equal(h.api.snapshot().state,null);assert.match(h.api.snapshot().error,/access denied/);});
test('lost mutation response reuses the exact request receipt and payload',async()=>{const h=controller();let n=0;h.setReply(()=>{if(!n++)throw new Error('connection lost');return {ok:true};});const body={action:'save_inputs',run_id:'r',expected_revision:4,inputs:{a:1}};await assert.rejects(h.api.command(body));await h.api.command(body);assert.deepEqual(h.calls[0].body,h.calls[1].body);});
test('definitive rejection retires its receipt instead of replaying invalid intent',async()=>{const h=controller();let n=0;h.setReply(()=>n++?{ok:true}:{ok:false,error:{message:'expired'},httpError:true,status:409});const body={action:'save_inputs',run_id:'r',inputs:{a:1}};await assert.rejects(h.api.command(body));await h.api.command(body);assert.notEqual(h.calls[0].body.request_id,h.calls[1].body.request_id);});
test('operations and workspace receipts are distinct authenticated command paths',async()=>{const h=controller();await h.api.command({action:'save_inputs'});await h.api.operationsCommand({action:'execute_job'});assert.equal(h.calls[0].url,'/api/ees-work/workspace/command');assert.equal(h.calls[1].url,'/api/ees-work/operations');assert.match(h.calls[1].options.headers.Authorization,/Bearer /);});
test('late successful mutation cannot repopulate another account or scope',async()=>{const h=controller(),pending=deferred();h.setReply(()=>pending.promise);const waiting=h.api.command({action:'save_inputs'});h.setAuth('actor-b');pending.resolve({ok:true,run:{private:'a'}});assert.equal(await waiting,null);assert.equal(h.api.snapshot().state,null);});
test('normalization selects the exact current attempt and preserves historical decisions',()=>{const h=controller();const result=h.api.normalized({run:{jobs:{j:{current_attempt:'old',result_revision:1,decisions:[{item_id:'one',attempt_id:'old',result_revision:1},{item_id:'two',attempt_id:'new',result_revision:2}]}},attempts:[{id:'old',job_id:'j',result:{name:'selected'}},{id:'new',job_id:'j',result:{name:'unrelated'}}]}});assert.equal(result.run.jobs.j.result.name,'selected');assert.equal(result.run.jobs.j.decision_history.length,2);assert.equal(result.run.jobs.j.decisions.two,undefined);});
test('redacted evidence stays null instead of substituting another readable attempt',()=>{const h=controller();const result=h.api.normalized({run:{jobs:{j:{current_attempt:'redacted',result_revision:2}},attempts:[{id:'previous',job_id:'j',result:{private:'old'}},{id:'redacted',job_id:'j',result:null,evidence_access:'requires_current_source_access'}]}});assert.equal(result.run.jobs.j.result,null);});
test('Native model list keeps actual allowed identities and excludes direct embedding routes',async()=>{const h=controller();h.setReply(()=>({data:[{id:'allowed',name:'Native name'},{id:'direct',direct:true},{id:'embedding',type:'embedding'}]}));const list=await h.api.models();assert.equal(list.length,1);assert.equal(list[0].name,'Native name');assert.equal(h.context.document.body.dataset.eesModelCount,'1');});
test('AI reference never contains Native authorization tokens or confirmation intents',()=>{const h=controller();h.api.setSelection({workflow_id:'workflow',run_id:'run',job_id:'job'});const serialized=JSON.stringify(h.api.reference());assert.doesNotMatch(serialized,/actor-a-token|Bearer|intent_token/);assert.match(serialized,/workflow/);});

test('late confirmation is rejected after account or selected work context changes',async()=>{for(const change of ['account','job']){const h=controller(),pending=deferred();h.setDialog(()=>pending.promise);const waiting=h.api.confirmDialog({title:'확인'});if(change==='account')h.setAuth('other');else h.api.setSelection({job_id:'other'});pending.resolve(true);assert.equal(await waiting,false);assert.equal(h.calls.length,0);}});

test('first workspace read refetches after default system selection before accepting operations',async()=>{const h=controller();h.api.setRestored(false);h.setReply(call=>call.url.startsWith('/api/ees-work/operations')?{ok:true,models:[]}:{ok:true,capabilities:{actor_id:'a'},systems:['EMS'],workflows:[],runs:[],my_work:[],ui_state:{revision:0,state:{}}});const state=await h.api.refresh();assert.ok(state);assert.equal(h.api.snapshot().selection.system_id,'EMS');assert.equal(h.calls.filter(call=>call.url.startsWith('/api/ees-work/workspace?')).length,2);assert.equal(h.renders.length,1);});


test('allowed model count survives a work selection change but not account change',async()=>{for(const kind of ['work','account']){const h=controller(),pending=deferred();h.setReply(()=>pending.promise);const waiting=h.api.models();if(kind==='work')h.api.setSelection({system_id:'EMS'});else h.setAuth('new-account');pending.resolve({data:[{id:'one'}]});const result=await waiting;assert.equal(result.length,kind==='work'?1:0);assert.equal(h.context.document.body.dataset.eesModelCount,kind==='work'?'1':undefined);}});
test('read-only tab changes retain polling rather than stopping current execution observation',async()=>{const h=controller();await h.api.select({tab:'history'},{fetch:false});assert.equal(h.timers.size,2);assert.equal(h.calls.length,0);});
test('returning from a Native workspace page starts a fresh workspace read',async()=>{const h=controller();h.api.sync();await new Promise(resolve=>setImmediate(resolve));h.context.location.pathname='/workspace/models';h.context.document.querySelector=()=>null;h.api.sync();h.context.location.pathname='/';h.context.document.querySelector=()=>({});h.api.sync();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.calls.filter(call=>call.url.startsWith('/api/ees-work/workspace?')).length,2);});
function optionHarness(){const h=controller();h.api.setSelection({workflow_id:'w',run_id:'r',job_id:'j',tab:'current'});h.api.setState({run:{id:'r',revision:2,definition:{nodes:{j:{id:'j',inputs:[{id:'project',type:'text'},{id:'cr',type:'single',options_source:'tool',options:['forbidden-static']}]}}},jobs:{j:{effective_inputs:{project:'old'}}}},settings:{values:{},revision:0}});let inputs={project:'old'};h.view.readInputs=()=>({inputs});return {...h,setInputs:values=>{inputs=values;}};}
test('dynamic options use authenticated current-job inputs and never send an execution command',async()=>{const h=optionHarness();h.setInputs({project:'new',unrelated:'do-not-send'});h.setReply(()=>({ok:true,options:[{id:'CR-1',name:'현재 CR'}],source:{kind:'tool'},context:{revision:2}}));await h.api.loadOptions();assert.equal(h.calls[0].url,'/api/ees-work/workspace/options');assert.deepEqual(h.calls[0].body.inputs,{project:'new'});assert.equal(h.calls[0].body.action,undefined);assert.match(h.calls[0].options.headers.Authorization,/Bearer/);assert.equal(h.api.snapshot().state.input_options.cr.status,'ready');});
test('late option results cannot replace a changed input dependency or another job',async()=>{for(const change of ['input','job','account']){const h=optionHarness(),pending=deferred();h.setReply(()=>pending.promise);const waiting=h.api.loadOptions();if(change==='input')h.setInputs({project:'changed'});else if(change==='job')h.api.setSelection({job_id:'other'});else h.setAuth('other');pending.resolve({ok:true,options:[{id:'stale'}]});await waiting;assert.equal(h.api.snapshot().state.input_options.cr.status,'loading');assert.equal(h.api.snapshot().state.input_options.cr.options.length,0);}});
test('dynamic option failure disables selection without falling back to manual examples',async()=>{const h=optionHarness();h.setReply(()=>({ok:false,httpError:true,status:403,error:{message:'source access denied'}}));await h.api.loadOptions();const lookup=h.api.snapshot().state.input_options.cr;const out=html('workInputHTML(field,undefined,{lookup})',{field:{id:'cr',type:'single',options_source:'tool',options:['forbidden-static']},lookup});assert.match(out,/<select[^>]* disabled/);assert.match(out,/source access denied/);assert.doesNotMatch(out,/forbidden-static/);});
test('removed dynamic selection stays explicit and no returned option is automatically chosen',()=>{const out=html('workInputHTML(field,"removed",{lookup})',{field:{id:'cr',type:'single',options_source:'common'},lookup:{status:'ready',options:[{id:'allowed',name:'현재 값'}],source:{kind:'common'}}});assert.match(out,/이전 선택 · 현재 목록 확인 필요/);assert.match(out,/removed[^>]* selected/);assert.doesNotMatch(out,/allowed[^>]* selected/);});


test('held Enter or Space cannot repeat a mutation while its ordinary first click still runs',async()=>{const h=controller();let prevented=0,stopped=0;const target={dataset:{action:'execute'},closest:selector=>selector==='[data-mutation]'||selector==='[data-ees-work]'||selector==='button[data-action]'?target:null};for(const key of ['Enter',' '])h.api.handleEvent({type:'keydown',key,repeat:true,target,preventDefault:()=>prevented++,stopImmediatePropagation:()=>stopped++});assert.equal(prevented,2);assert.equal(stopped,2);assert.equal(h.calls.length,0);h.api.setState({run:{revision:2}});h.api.setSelection({run_id:'r',job_id:'j'});h.api.handleEvent({type:'click',target,preventDefault:()=>{}});await new Promise(resolve=>setImmediate(resolve));assert.equal(h.calls.filter(call=>call.body?.action==='execute_job').length,1);});
test('scope execution uses the selected P or T and refuses unsaved run drafts',async()=>{const h=controller();h.api.setState({run:{revision:4}});h.api.setSelection({run_id:'r'});h.view.hasPendingInputs=()=>true;await h.api.handleClick({dataset:{action:'execute_scope',nodeId:'t1'}});assert.equal(h.calls.length,0);h.view.hasPendingInputs=()=>false;await h.api.handleClick({dataset:{action:'execute_scope',nodeId:'t1'}});assert.equal(h.calls[0].url,'/api/ees-work/operations');assert.equal(h.calls[0].body.node_id,'t1');assert.equal(h.calls[0].body.expected_revision,4);});


test('admin management renders existing Native identities and is absent for ordinary participants',()=>{const data={capabilities:{is_admin:true},factories:[{id:'f',name:'실제 등록',system_id:'EMS',revision:1}],access:[{id:'a',system_id:'EMS',factory_id:'f',principal_kind:'group',principal_id:'native-id',roles:['manager'],active:1}],people:[{name:'현재 그룹',value:{kind:'group',id:'native-id'}}]};const out=html('workAdminHTML(data)',{data});assert.match(out,/현재 그룹/);assert.match(out,/native-id/);assert.match(out,/data-action="admin_factory"/);assert.match(out,/data-action="admin_access"/);assert.doesNotMatch(html('workAdminHTML({capabilities:{is_admin:false}})'),/data-action=/);});
test('admin dialog refuses nonadmin identity before any write or new dialog',async()=>{const h=controller();h.api.setState({capabilities:{is_admin:false}});await assert.rejects(h.api.adminDialog('access'),/관리자/);assert.equal(h.calls.length,0);});
test('text export formats only fetched run history and retains redacted-source notice',()=>{const out=html('workExportText(document)',{document:{exported_at:'now',ui_state:{secret:'never-export'},run:{id:'r',version:1,status:'open',attempts:[{job_id:'j',number:1,status:'failed',inputs:{v:'historic'},result:null,evidence_access:'requires_current_source_access'}],jobs:{j:{decisions:[{item_id:'job',result_revision:1,verdict:'unknown',actor_id:'a'}]}}}}});assert.match(out,/historic/);assert.match(out,/원본 접근 권한 확인 필요/);assert.match(out,/unknown/);assert.doesNotMatch(out,/never-export/);});
test('legacy records have readonly navigation and escaped values with no execution controls',()=>{const out=html('workLegacyHTML(legacy)',{legacy:{read_only:true,records:[{id:'old',process_name:'<script>name</script>',simulation:true,status:'failed'}]}});assert.match(out,/사용 중지/);assert.match(out,/시뮬레이션/);assert.match(out,/open_legacy/);assert.doesNotMatch(out,/<script|data-action="execute|data-action="confirm/);});
test('authenticated Native management navigation suspends view without clearing private drafts',async()=>{const h=controller();let reset=0,suspend=0;h.view.reset=()=>reset++;h.view.suspend=()=>suspend++;h.api.sync();await new Promise(resolve=>setImmediate(resolve));h.context.location.pathname='/workspace/skills';h.context.document.querySelector=()=>null;h.api.sync();assert.equal(suspend,1);assert.equal(reset,0);h.setAuth('other-account');h.api.sync();assert.equal(reset,1);});


test('AI item badge disappears only when a saved decision for that item is present',()=>{const job={result_block:'item_verdict'},saved={result:{items:[{id:'a',ai_suggestion:'적합'},{id:'b',ai_suggestion:'미흡'}]},decisions:{a:{verdict:'completed'}}};const out=html('workResultHTML(job,saved)',{job,saved});assert.equal((out.match(/AI 제안 ·/g) || []).length,1);assert.match(out,/미흡 · 사람 미확정/);});
test('date-only and timezone-qualified saved inputs preserve their exact stored value',()=>{assert.match(html('workInputHTML({id:"day",type:"datetime"},"2026-10-02")'),/type="date"[^>]*value="2026-10-02"/);assert.match(html('workInputHTML({id:"time",type:"datetime"},"2026-10-02T09:00:00+09:00")'),/type="text"[^>]*value="2026-10-02T09:00:00\+09:00"/);});


test('first Native chat proposal accepts only the creation-bound old context without a DB write',()=>{const h=controller();h.api.setSelection({mode:'author',workflow_id:'w'});h.api.setState({workflow:{revision:2}});h.designer.readDraft=()=>({revision:2,definition:{id:'w',name:'draft'}});const source=h.api.context(),creation=h.api.beginChatCreation();h.api.finishChatCreation(creation,'native-new');h.context.location.pathname='/c/native-new';const result=h.api.acceptNativeProposal('native-new',{context_id:source});assert.equal(result.ok,true);assert.equal(h.calls.length,0);});
test('first-chat context alias rejects another chat account changed version draft or scope',()=>{for(const change of ['chat','account','version','draft','scope']){const h=controller();let name='draft';h.api.setSelection({mode:'author',workflow_id:'w'});h.api.setState({workflow:{revision:2}});h.designer.readDraft=()=>({revision:2,definition:{id:'w',name}});const source=h.api.context(),creation=h.api.beginChatCreation();h.api.finishChatCreation(creation,'native-new');h.context.location.pathname='/c/native-new';if(change==='chat')h.context.location.pathname='/c/unrelated';if(change==='account')h.setAuth('other');if(change==='version')h.api.setState({workflow:{revision:3}});if(change==='draft')name='changed';if(change==='scope')h.api.setSelection({factory_id:'other'});assert.equal(h.api.acceptNativeProposal(h.context.location.pathname.slice(3),{context_id:source}).ok,false);assert.equal(h.calls.length,0);}});
test('unmatched Native creation finish cannot bless an arbitrary old chat context',()=>{const h=controller();h.api.setSelection({workflow_id:'w'});const source=h.api.context();h.api.finishChatCreation('not-issued','native-new');h.context.location.pathname='/c/native-new';assert.equal(h.api.acceptNativeProposal('native-new',{context_id:source}).ok,false);assert.equal(h.api.beginChatCreation(),'');});


test('start-run mutation uses workflow revision rather than absent run revision',async()=>{const h=controller();h.api.setState({workflow:{revision:7}});await h.api.command({action:'start_run',workflow_id:'w',version:1});assert.equal(h.calls[0].body.expected_revision,7);});
test('start dialog retains its captured workflow revision across a concurrent refresh',async()=>{const h=controller(),pending=deferred();h.context.document.querySelector=()=>({addEventListener(){}});h.api.setState({workflow:{id:'w',revision:6,published_version:1,versions:[{version:1}]}});h.api.setSelection({workflow_id:'w'});h.setDialog(()=>pending.promise);const waiting=h.api.handleClick({dataset:{action:'start_run'}});h.api.setState({workflow:{id:'w',revision:7,published_version:2,versions:[{version:2}]}});pending.resolve(true);await waiting;assert.equal(h.calls.find(call=>call.body?.action==='start_run').body.expected_revision,6);assert.equal(h.calls.find(call=>call.body?.action==='start_run').body.version,1);});
test('successful read polling preserves command rejection until successful command or explicit context change',async()=>{const h=controller();h.api.setState({workflow:{revision:3}});h.setReply(call=>call.options.method==='POST'?{ok:false,httpError:true,status:409,error:{message:'revision conflict'}}:{ok:true,systems:[],workflows:[],runs:[],ui_state:{revision:0,state:{}}});await assert.rejects(h.api.command({action:'start_run'}));await h.api.refresh();assert.match(h.api.snapshot().error,/revision conflict/);h.setReply(()=>({ok:true}));await h.api.command({action:'save_inputs'});assert.equal(h.api.snapshot().error,'');});


test('first-chat alias is retired when navigating through another conversation',async()=>{const h=controller();h.api.setSelection({mode:'author',workflow_id:'w'});h.api.setState({workflow:{revision:2}});h.designer.readDraft=()=>({revision:2,definition:{id:'w'}});const source=h.api.context(),creation=h.api.beginChatCreation();h.api.finishChatCreation(creation,'first');h.context.location.pathname='/c/other';h.api.sync();await new Promise(resolve=>setImmediate(resolve));h.api.setState({workflow:{revision:2}});h.context.location.pathname='/c/first';assert.equal(h.api.acceptNativeProposal('first',{context_id:source}).ok,false);});


test('saving one factory setting never promotes unchanged inherited values to overrides',()=>{const settings={values:{own:0,inherited:'base',untouched:'default'},overrides:{own:0}},fields=[{id:'own',scope:'workflow'},{id:'inherited',scope:'workflow'},{id:'untouched',scope:'factory'}];const result=html('workSettingsOverrides(settings,draft,fields)',{settings,draft:{own:0,inherited:'edited',untouched:'default'},fields});assert.deepEqual(JSON.parse(JSON.stringify(result)),{own:0,inherited:'edited'});assert.deepEqual(JSON.parse(JSON.stringify(html('workSettingsOverrides(settings,settings.values,fields)',{settings,fields}))),{own:0});});
test('run settings target the run factory while viewing all factories and retain raw overrides',()=>{const h=controller();h.api.setSelection({factory_id:''});const result=h.api.normalized({workflow:{settings:[{factory_id:'',values:{shared:'base'},revision:1},{factory_id:'actual-run-factory',values:{specific:false},revision:3}]},run:{factory_id:'actual-run-factory',jobs:{},attempts:[]}});assert.equal(result.settings.factory_id,'actual-run-factory');assert.equal(result.settings.revision,3);assert.deepEqual(JSON.parse(JSON.stringify(result.settings.overrides)),{specific:false});assert.equal(result.settings.values.shared,'base');});
test('existing empty text and empty list stay distinct from never-assigned optional values',()=>{const fields=[{name:'text',value:'',dataset:{inputType:'text',valuePresent:'true'}},{name:'list',value:'',dataset:{inputType:'list',valuePresent:'true'}},{name:'unset',value:'',dataset:{inputType:'text',valuePresent:'false'}}];const result=html('workReadInputs(form)',{form:{querySelectorAll:()=>fields}});assert.equal(result.text,'');assert.equal(result.list.length,0);assert.equal(result.unset,undefined);});


test('readonly Work tool setup needs Native admin and cancelling preview never writes assets',async()=>{const h=controller();h.api.setState({capabilities:{is_admin:false}});await assert.rejects(h.api.setupWorkTool(),/관리자/);assert.equal(h.calls.length,0);h.api.setState({capabilities:{is_admin:true},people:[],native_groups:[]});h.context.document.querySelector=()=>({addEventListener(){}});h.setReply(()=>({state:'missing',id:'ees_workflow',source_sha256:'actual-source',expected_token:'preview-hash',functions:['list','propose']}));h.setDialog(()=>Promise.resolve(false));await h.api.setupWorkTool();assert.equal(h.calls.length,1);assert.equal(h.calls[0].url,'/api/v1/ees/assets/work-tool/status');assert.equal(h.calls[0].options.method,'GET');});
test('explicit Work tool confirmation sends preview token source hash and no public grants',async()=>{const h=controller();h.api.setState({capabilities:{is_admin:true},people:[],native_groups:[]});h.context.document.querySelector=()=>({addEventListener(){}});h.setReply(call=>call.url.endsWith('/status')?{state:'missing',id:'ees_workflow',source_sha256:'source-hash',expected_token:'preview-token',functions:['propose']}:call.url.endsWith('/setup')?{ok:true,changed:true}:{ok:true,systems:[],workflows:[],runs:[],ui_state:{revision:0,state:{}}});h.setDialog(()=>Promise.resolve(true));await h.api.setupWorkTool();const post=h.calls.find(call=>call.url.endsWith('/setup'));assert.equal(post.body.expected_token,'preview-token');assert.equal(post.body.source_sha256,'source-hash');assert.equal(post.body.confirmation,'register_readonly_work_tool');assert.deepEqual(post.body.access_grants,[]);});


test('input AI proposal preview and apply modify only the private draft until explicit save',()=>{const h=controller(),run={id:'r',workflow_id:'w',revision:2,definition:{nodes:{j:{inputs:[{id:'value',scope:'run',type:'text'}]}}}};h.api.setSelection({run_id:'r',workflow_id:'w',job_id:'j',tab:'current'});h.api.setState({run});h.view.readInputs=()=>({inputs:{old:'keep'},revision:2});let applied;h.view.applyInputValues=values=>{applied=values;};const preview=h.api.previewInputProposal({proposal_kind:'inputs',run_id:'r',workflow_id:'w',job_id:'j',base_revision:2,proposal:{value:'suggested'}});assert.equal(preview.saved,false);assert.equal(preview.executed,false);assert.equal(applied,undefined);h.api.applyInputProposal();assert.equal(applied.value,'suggested');assert.equal(h.calls.length,0);});
test('AI input preview rejects unknown setting fields and stale apply after user typing',()=>{const h=controller(),run={id:'r',workflow_id:'w',revision:2,definition:{nodes:{j:{inputs:[{id:'value',scope:'run'},{id:'system_setting',scope:'workflow'}]}}}};h.api.setSelection({run_id:'r',workflow_id:'w',job_id:'j',tab:'current'});h.api.setState({run});let inputs={value:'before'};h.view.readInputs=()=>({inputs,revision:2});assert.throws(()=>h.api.previewInputProposal({proposal_kind:'inputs',run_id:'r',workflow_id:'w',job_id:'j',base_revision:2,proposal:{system_setting:'forbidden'}}));h.api.previewInputProposal({proposal_kind:'inputs',run_id:'r',workflow_id:'w',job_id:'j',base_revision:2,proposal:{value:'AI'}});inputs={value:'typed-later'};assert.throws(()=>h.api.applyInputProposal(),/바뀌었습니다/);assert.equal(h.calls.length,0);});


test('per-message reference records exact immutable attempt and version without chat body or secrets',()=>{const h=controller();h.api.setSelection({workflow_id:'w',run_id:'r',job_id:'j'});h.api.setState({run:{version:2,revision:9,system_id:'EMS',factory_id:'f',jobs:{j:{current_attempt:'attempt-old',result_revision:3}}}});const ref=h.api.reference();assert.equal(ref.attempt_id,'attempt-old');assert.equal(ref.version,2);assert.equal(ref.result_revision,3);assert.doesNotMatch(JSON.stringify(ref),/token|chat_body|intent/);});
test('historical message chip never substitutes latest evidence for an old or absent attempt',()=>{const run={id:'r',version:1,jobs:{},attempts:[{id:'a1',job_id:'j',number:1,result:{value:'old exact'}},{id:'a2',job_id:'j',number:2,result:{value:'newest unrelated'}}]};const out=html('workHistoricalReferenceHTML(run,reference)',{run,reference:{run_id:'r',job_id:'j',attempt_id:'a1',version:1,result_revision:1}});assert.match(out,/old exact/);assert.doesNotMatch(out,/newest unrelated/);assert.match(html('workHistoricalReferenceHTML(run,{run_id:"r",job_id:"j"})',{run}),/당시 실행 시도 식별자가 기록되지 않았습니다/);assert.doesNotMatch(html('workHistoricalReferenceHTML(run,{run_id:"r",job_id:"j",attempt_id:"missing"})',{run}),/old exact|newest unrelated/);});

test('execution names the sole currently authorized model and preserves explicit multi-model choice',async()=>{
 const cases=[{models:[{id:'sole'}],expected:'sole'},{models:[{id:'first'},{id:'arena-model'}]},{models:[{id:'first'},{id:'arena-model'}],selected:'arena-model',expected:'arena-model'}];
 for(const action of ['execute','execute_scope'])for(const {models,selected,expected} of cases){const h=controller();h.context.document.querySelector=()=>({value:selected});h.api.setState({run:{revision:4},operations:{models}});h.api.setSelection({run_id:'r',job_id:'j'});await h.api.handleClick({dataset:{action,nodeId:'p'}});assert.equal(h.calls[0].body.model_id,expected);}
});
test('single model label is visible while multiple actual models retain the chooser',()=>{const single=html('workExecutionModelHTML(operations)',{operations:{models:[{id:'only',name:'현재 모델'}]}});assert.match(single,/AI 모델 · 현재 모델/);assert.doesNotMatch(single,/<select/);const multi=html('workExecutionModelHTML(operations)',{operations:{models:[{id:'first'},{id:'arena-model'}]}});assert.match(multi,/id="ees-work-execution-model"/);assert.match(multi,/arena-model/);});
test('unavailable dynamic inputs explain why AI omitted them without adding values',()=>{const h=controller(),run={id:'r',workflow_id:'w',revision:2,definition:{nodes:{j:{inputs:[{id:'value',scope:'run',type:'text'},{id:'cr',name:'CR',scope:'run',type:'single'}]}}}};h.api.setSelection({run_id:'r',workflow_id:'w',job_id:'j'});h.api.setState({run});h.view.readInputs=()=>({inputs:{},revision:2});h.api.previewInputProposal({proposal_kind:'inputs',run_id:'r',workflow_id:'w',job_id:'j',base_revision:2,proposal:{value:'draft'},unresolved_fields:[{field_id:'cr',reason:'options_dependency_required'}]});const proposal=h.renders.at(-1).state.input_proposal;assert.match(proposal.warnings[0],/CR · 선행 입력/);assert.equal(proposal.values.cr,undefined);assert.equal(h.calls.length,0);});
