const test=require('node:test'),assert=require('node:assert/strict');
const {renderer,run}=require('./ees_workspace_ui_fixture.cjs');
const fixture=()=>{const context=renderer();return {context,drafts:run(context,'createWorkInputDrafts()')};};
test('typed draft preserves false zero empty arrays and an explicitly removed optional field',()=>{const {drafts}=fixture();drafts.edit('a',{enabled:false,count:0,list:[]},1,{optional:'old'});const value=drafts.read('a',{optional:'old'},1);assert.equal(value.inputs.enabled,false);assert.equal(value.inputs.count,0);assert.equal(value.inputs.optional,undefined);assert.equal(value.dirty,true);});
test('independent concurrent input changes cannot be silently overwritten',()=>{const {drafts}=fixture();drafts.edit('a',{a:2,b:1},1,{a:1,b:1});const value=drafts.read('a',{a:1,b:2},2);assert.equal(value.conflict,true);assert.equal(value.revision,1);assert.equal(value.inputs.b,1);});
test('server revision without input change retains the draft without a false conflict',()=>{const {drafts}=fixture();drafts.edit('a',{a:2},1,{a:1});assert.equal(drafts.read('a',{a:1},2).conflict,false);});
test('drafts remain isolated between account scope run and job keys',()=>{const {drafts}=fixture();drafts.edit('actor-a/EMS/factory/run/job',{value:'private'},1,{});for(const key of ['actor-b/EMS/factory/run/job','actor-a/FDC/factory/run/job','actor-a/EMS/other/run/job','actor-a/EMS/factory/other/job','actor-a/EMS/factory/run/other'])assert.equal(drafts.read(key,{},1).inputs.value,undefined);});
test('acknowledging a save never overwrites typing after the request',()=>{const {drafts}=fixture();drafts.edit('a',{text:'first'},1,{});const first=drafts.read('a',{},1);drafts.edit('a',{text:'second'},1,{});drafts.acknowledge('a',first.serial,2,{text:'first'});const current=drafts.read('a',{text:'first'},2);assert.equal(current.inputs.text,'second');assert.equal(current.revision,2);assert.equal(current.dirty,true);});
test('matching save receipt clears only its own acknowledged draft',()=>{const {drafts}=fixture();drafts.edit('a',{text:'first'},1,{});drafts.edit('b',{text:'other'},1,{});drafts.acknowledge('a',1,2,{text:'first'});assert.equal(drafts.read('a',{text:'first'},2).dirty,false);assert.equal(drafts.read('b',{},1).inputs.text,'other');});
test('explicit discard restores saved values without changing server objects',()=>{const {drafts}=fixture();const saved={a:1};drafts.edit('a',{a:2},1,saved);drafts.discard('a');assert.equal(drafts.read('a',saved,1).inputs.a,1);assert.deepEqual(saved,{a:1});});
test('account reset clears every private draft',()=>{const {drafts}=fixture();drafts.edit('a',{private:'value'},1,{});drafts.clear();assert.equal(drafts.read('a',{},1).dirty,false);assert.equal(drafts.read('a',{},1).inputs.private,undefined);});
test('returned draft snapshots cannot mutate stored drafts or caller inputs',()=>{const {drafts}=fixture(),input={list:['a']};drafts.edit('a',input,1,{});input.list.push('b');const result=drafts.read('a',{},1);result.inputs.list.push('c');assert.equal(drafts.read('a',{},1).inputs.list.length,1);});
test('invalid numeric input fails before a save payload is constructed',()=>{const context=renderer();context.form={querySelectorAll:()=>[{disabled:false,name:'number',value:'NaN',dataset:{inputType:'number'}}]};assert.throws(()=>run(context,'workReadInputs(form)'),/숫자/);});


test('render recapture after a successful save cannot turn identical server values into a conflict',()=>{const h=renderer(),drafts=run(h,'createWorkInputDrafts()');drafts.edit('r/j',{value:'saved'},1,{});const first=drafts.read('r/j',{},1);drafts.acknowledge('r/j',first.serial,2,{value:'saved'});drafts.edit('r/j',{value:'saved'},1,{});const next=drafts.read('r/j',{value:'saved'},2);assert.equal(next.dirty,false);assert.equal(next.conflict,false);assert.equal(next.revision,2);});
test('unchanged server inputs advance the CAS base while preserving unsaved local input',()=>{const h=renderer(),drafts=run(h,'createWorkInputDrafts()');drafts.edit('r/j',{value:'local'},1,{value:'server'});const next=drafts.read('r/j',{value:'server'},3);assert.equal(next.inputs.value,'local');assert.equal(next.dirty,true);assert.equal(next.conflict,false);assert.equal(next.revision,3);});
